#include "6_generated_code.h"
#include <math.h>
#include <string.h>
#include <limits.h>
#define PI 3.14159265358979323846f
#define RAD 0.01745329251994329577f
#define DEG 57.29577951308232f
float qw=1.0f,qx=0.0f,qy=0.0f,qz=0.0f,gravityX=0.0f,gravityY=0.0f,gravityZ=1.0f,integralFBx=0.0f,integralFBy=0.0f,integralFBz=0.0f,twoKp=.8f,twoKi=.002f,beta=.01f,baseZacc=0.0f; bool sensfusion6IsInit=false,sensfusion6IsCalibrated=false;
PidObject pidRoll,pidPitch,pidYaw,pidRollRate,pidPitchRate,pidYawRate; bool thrustLocked=false,commanderModeSet=false; SupervisorState supervisorState=supervisorStateLocked; uint32_t supervisorConditionBits=0; TestState healthTestState=testDone; uint8_t motorPass=0,batteryPass=0; float batterySag=0;
StateEstimateLog stateEstimate={0}; Axis3Log gyro={0},acc={0}; BaroLog baro={0}; MotorLog motor={0}; Sensfusion6Log sensfusion6Log={0}; SupervisorLog supervisorLog={0}; HealthLog healthLog={0};
static uint32_t nowTick,flightTick,tiltTick,rpmTick,spinTick,cmdTick; static bool flightSeen,armed,crashed,tiltUpside,autoArm,tumbleEnabled,propReq,batReq; static SensorData supervisorSensors; static uint32_t ratios[4],idleThrust; static int32_t rpms[4]; static float crashGs,freeFallGs,tiltAccZ,upsideAccZ; static uint32_t tiltTimeout,upsideTimeout,spinTimeout; static Setpoint activeSetpoint,highLevelSetpoint; static bool highLevelPending,stabilizerReady; static int activePriority=COMMANDER_PRIORITY_LOWEST; static EstimatorMeasurement ef[16]; static uint8_t eh,et,ec; static int16_t actuatorRoll,actuatorPitch,actuatorYaw; static float controlDt=.002f;
static float limitf(float v,float lo,float hi){return v<lo?lo:v>hi?hi:v;} static uint16_t pwmf(float v){v=limitf(v,0,65535);return (uint16_t)lroundf(v);} static void syncFusionLog(void){sensfusion6Log=(Sensfusion6Log){qw,qx,qy,qz,gravityX,gravityY,gravityZ,baseZacc,sensfusion6IsInit,sensfusion6IsCalibrated};}
int16_t saturateSignedInt16(int32_t v){return v>INT16_MAX?INT16_MAX:v<-(int32_t)INT16_MAX?-(int16_t)INT16_MAX:(int16_t)v;} float capAngle(float a){while(a>180.0f)a-=360.0f;while(a<-180.0f)a+=360.0f;return a;} float invSqrt(float x){union{float f;uint32_t i;}u;if(x<=0)return 0;u.f=x;u.i=0x5f3759df-(u.i>>1);return u.f*(1.5f-.5f*x*u.f*u.f);}
void estimatedGravityDirection(float w,float x,float y,float z,float *gx,float *gy,float *gz){if(gx)*gx=2.0f*(x*z-w*y);if(gy)*gy=2.0f*(w*x+y*z);if(gz)*gz=w*w-x*x-y*y+z*z;}
void sensfusion6Init(void){if(sensfusion6IsInit)return;qw=1;qx=qy=qz=0;gravityX=gravityY=0;gravityZ=1;integralFBx=integralFBy=integralFBz=baseZacc=0;sensfusion6IsCalibrated=false;sensfusion6IsInit=true;syncFusionLog();} bool sensfusion6Test(void){return sensfusion6IsInit;}
void sensfusion6UpdateQ(float gx,float gy,float gz,float ax,float ay,float az,float dt){float n,ex=0,ey=0,ez=0,w,x,y,z,s;if(!sensfusion6IsInit)sensfusion6Init();if(dt<0)dt=0;n=sqrtf(ax*ax+ay*ay+az*az);if(n>0){ax/=n;ay/=n;az/=n;estimatedGravityDirection(qw,qx,qy,qz,&gravityX,&gravityY,&gravityZ);ex=ay*gravityZ-az*gravityY;ey=az*gravityX-ax*gravityZ;ez=ax*gravityY-ay*gravityX;if(twoKi>0){integralFBx+=twoKi*ex*dt;integralFBy+=twoKi*ey*dt;integralFBz+=twoKi*ez*dt;gx+=integralFBx;gy+=integralFBy;gz+=integralFBz;}else integralFBx=integralFBy=integralFBz=0;#ifdef CONFIG_IMU_MADGWICK_QUATERNION
 gx+=beta*ex;gy+=beta*ey;gz+=beta*ez;
#else
 gx+=twoKp*ex;gy+=twoKp*ey;gz+=twoKp*ez;
#endif
 if(!sensfusion6IsCalibrated){baseZacc=ax*gravityX+ay*gravityY+az*gravityZ;sensfusion6IsCalibrated=true;}}else integralFBx=integralFBy=integralFBz=0;w=qw-.5f*dt*(qx*gx+qy*gy+qz*gz);x=qx+.5f*dt*(qw*gx+qy*gz-qz*gy);y=qy+.5f*dt*(qw*gy-qx*gz+qz*gx);z=qz+.5f*dt*(qw*gz+qx*gy-qy*gx);s=invSqrt(w*w+x*x+y*y+z*z);if(s){qw=w*s;qx=x*s;qy=y*s;qz=z*s;}estimatedGravityDirection(qw,qx,qy,qz,&gravityX,&gravityY,&gravityZ);syncFusionLog();}
void sensfusion6GetEulerRPY(float *r,float *p,float *y){float gx,gy,gz;estimatedGravityDirection(qw,qx,qy,qz,&gx,&gy,&gz);gravityX=gx;gravityY=gy;gravityZ=gz;if(r)*r=atan2f(2*(qw*qx+qy*qz),1-2*(qx*qx+qy*qy))*DEG;if(p)*p=asinf(limitf(-gx,-1,1))*DEG;if(y)*y=atan2f(2*(qw*qz+qx*qy),1-2*(qy*qy+qz*qz))*DEG;syncFusionLog();} void sensfusion6GetQuaternion(float *w,float *x,float *y,float *z){if(w)*w=qw;if(x)*x=qx;if(y)*y=qy;if(z)*z=qz;} float sensfusion6GetAccZ(float x,float y,float z){estimatedGravityDirection(qw,qx,qy,qz,&gravityX,&gravityY,&gravityZ);return x*gravityX+y*gravityY+z*gravityZ;} float sensfusion6GetAccZWithoutGravity(float x,float y,float z){return sensfusion6GetAccZ(x,y,z)-baseZacc;}
void powerDistributionLegacy(uint16_t t,int16_t r,int16_t p,int16_t y,MotorPower *o){int32_t R=r/2,P=p/2;if(!o)return;o->m1=(int32_t)t-R+P+y;o->m2=(int32_t)t-R-P-y;o->m3=(int32_t)t+R-P+y;o->m4=(int32_t)t+R+P-y;}
void powerDistributionForceTorque(float t,float tx,float ty,float tz,float arm,float k,float f[4]){float d=.25f*t,a=0,b=0,c=0;int i;if(!f)return;if(arm!=0)a=.25f*tx/(.707106781f*arm),b=.25f*ty/(.707106781f*arm);if(k!=0)c=.25f*tz/k;f[0]=d+a+b+c;f[1]=d-a-b-c;f[2]=d+a-b+c;f[3]=d-a+b-c;for(i=0;i<4;i++)if(f[i]<0)f[i]=0;}
void powerDistributionForce(const float f[4],uint16_t p[4]){int i;if(!f||!p)return;for(i=0;i<4;i++)p[i]=pwmf(limitf(f[i],0,1)*65535.0f);} void powerDistribution(const ControlData *c,MotorPower *m){float f[4];uint16_t p[4];if(!c||!m)return;if(c->controlMode==controlModeLegacy)powerDistributionLegacy(c->thrust,c->roll,c->pitch,c->yaw,m);else if(c->controlMode==controlModeForceTorque){powerDistributionForceTorque(c->thrustSi,c->torque.x,c->torque.y,c->torque.z,CRAZYFLIE_ARM_LENGTH_M,CRAZYFLIE_THRUST_TO_TORQUE,f);for(int i=0;i<4;i++)p[i]=pwmf(f[i]/CRAZYFLIE_MAX_MOTOR_FORCE_N*65535.0f);m->m1=p[0];m->m2=p[1];m->m3=p[2];m->m4=p[3];}else if(c->controlMode==controlModeForce){powerDistributionForce(c->normalizedForces,p);m->m1=p[0];m->m2=p[1];m->m3=p[2];m->m4=p[3];}}
int32_t capMinThrust(int32_t v,int32_t i){return v<i?i:v;} PowerCapResult powerDistributionCap(int32_t m[4],int32_t max,int32_t idle){PowerCapResult r={false,0};int32_t high;int i;if(!m)return r;high=m[0];for(i=1;i<4;i++)if(m[i]>high)high=m[i];if(high>max){r.isCapped=true;r.reduction=high-max;for(i=0;i<4;i++)m[i]=capMinThrust(m[i]-r.reduction,idle);}return r;} float batteryCompensation(float s,float o,float a){return o+a*(s-o);} uint16_t motorsCompensateBatteryVoltage(uint16_t t,float n,float a){return a<=0?t:pwmf((float)t*n/a);}
static void pidReset(PidObject *p,float e){if(!p)return;p->integral=0;p->prevError=e;p->output=0;p->initialized=true;} void attitudeControllerInit(float d){PidObject *p[6]={&pidRoll,&pidPitch,&pidYaw,&pidRollRate,&pidPitchRate,&pidYawRate};int i;controlDt=d>0?d:.002f;for(i=0;i<6;i++)if(!p[i]->initialized){p[i]->kp=1;p[i]->ki=p[i]->kd=p[i]->kff=0;pidReset(p[i],0);}} void attitudeControllerCorrectAttitudePID(float a,float b,float c,float d,float e,float f){pidRoll.output=b-a;pidPitch.output=d-c;pidYaw.output=f-e;} void attitudeControllerCorrectRatePID(float a,float b,float c,float d,float e,float f){actuatorRoll=saturateSignedInt16(lroundf(b-a));actuatorPitch=saturateSignedInt16(lroundf(d-c));actuatorYaw=saturateSignedInt16(lroundf(f-e));pidRollRate.output=actuatorRoll;pidPitchRate.output=actuatorPitch;pidYawRate.output=actuatorYaw;} void attitudeControllerResetAllPID(float a,float b,float c){pidReset(&pidRoll,a);pidReset(&pidPitch,b);pidReset(&pidYaw,c);pidReset(&pidRollRate,0);pidReset(&pidPitchRate,0);pidReset(&pidYawRate,0);} void attitudeControllerResetRollAttitudePID(float a){pidReset(&pidRoll,a);} void attitudeControllerResetPitchAttitudePID(float a){pidReset(&pidPitch,a);} void attitudeControllerGetActuatorOutput(int16_t *r,int16_t *p,int16_t *y){if(r)*r=actuatorRoll;if(p)*p=actuatorPitch;if(y)*y=actuatorYaw;} uint16_t positionControllerUpdate(const Setpoint *s,const State *t){float v;if(!s||!t)return 0;v=(float)s->thrust+1000*(s->position.z-t->position.z)+100*(s->velocity.z-t->velocity.z);return pwmf(v);}
void controllerPid(const SensorData *s,const Setpoint *p,const State *st,ControlData *c,float yd,float dt){float yaw,roll,pitch; if(!p||!st||!c)return;memset(c,0,sizeof(*c));if(p->thrust==0){attitudeControllerResetAllPID(st->attitude.roll,st->attitude.pitch,st->attitude.yaw);return;}yaw=p->mode.yaw==modeVelocity?st->attitude.yaw+p->attitudeRate.yaw*dt:p->attitude.yaw;if(p->mode.quat==modeAbs){Quaternion q=p->attitudeQuaternion;yaw=atan2f(2*(q.w*q.z+q.x*q.y),1-2*(q.y*q.y+q.z*q.z))*DEG;}if(yd!=0)yaw=st->attitude.yaw+limitf(yaw-st->attitude.yaw,-yd,yd);roll=p->mode.roll==modeVelocity?p->attitudeRate.roll:p->attitude.roll;pitch=p->mode.pitch==modeVelocity?p->attitudeRate.pitch:p->attitude.pitch;if(p->mode.roll==modeVelocity)pidReset(&pidRoll,st->attitude.roll);if(p->mode.pitch==modeVelocity)pidReset(&pidPitch,st->attitude.pitch);attitudeControllerCorrectRatePID(s?s->gyro.x:0,roll,s?-s->gyro.y:0,pitch,s?s->gyro.z:0,yaw);c->controlMode=controlModeLegacy;c->roll=actuatorRoll;c->pitch=actuatorPitch;c->yaw=-actuatorYaw;c->thrust=p->mode.z==modeDisable?p->thrust:positionControllerUpdate(p,st);}
void rotateYaw(float r,float p,float d,float *rp,float *pp){float c=cosf(d*RAD),s=sinf(d*RAD);if(rp)*rp=r*c-p*s;if(pp)*pp=r*s+p*c;}
void crtpCommanderRpytDecodeSetpoint(const CommanderCrtpLegacyValues *v,Setpoint *s,bool alt,bool pos,bool ps,StabilizationType rm,StabilizationType pm,StabilizationType ym,YawMode mode){if(!v||!s)return;memset(s,0,sizeof(*s));if(v->thrust==0)thrustLocked=false;if(alt){s->mode.z=modeVelocity;s->velocity.z=((float)v->thrust-32767.0f)/32767.0f;commanderModeSet=true;return;}commanderModeSet=false;if(thrustLocked||v->thrust<MIN_THRUST)return;s->thrust=v->thrust>MAX_THRUST?MAX_THRUST:v->thrust;if(ps&&v->thrust){s->mode.x=s->mode.y=s->mode.z=s->mode.yaw=modeAbs;s->mode.roll=s->mode.pitch=modeDisable;s->position=(Axis3f){-v->pitch,v->roll,v->thrust/1000.0f};s->attitude.yaw=v->yaw;s->thrust=0;return;}if(pos){s->mode.x=s->mode.y=modeVelocity;s->mode.roll=s->mode.pitch=modeDisable;s->velocity.x=v->pitch/30.0f;s->velocity.y=v->roll/30.0f;s->attitude.roll=s->attitude.pitch=0;return;}s->mode.roll=rm==RATE?modeVelocity:modeAbs;s->mode.pitch=pm==RATE?modeVelocity:modeAbs;s->mode.yaw=ym==RATE?modeVelocity:modeAbs;s->attitude=(Attitude){v->roll,v->pitch,v->yaw};s->attitudeRate=(Attitude){v->roll,v->pitch,ym==RATE?-v->yaw:v->yaw};if(mode==PLUSMODE)rotateYaw(s->attitude.roll,s->attitude.pitch,45,&s->attitude.roll,&s->attitude.pitch);else if(mode==CAREFREE)memset(s,0,sizeof(*s));}
void supervisorInit(void){supervisorState=supervisorStateLocked;supervisorConditionBits=0;armed=crashed=flightSeen=false;tiltTick=spinTick=0;} bool supervisorCanFly(void){return supervisorState==supervisorStateReadyToFly||supervisorState==supervisorStateFlying||supervisorState==supervisorStateWarningLevelOut||supervisorState==supervisorStateLanded;} bool supervisorCanArm(void){return supervisorState==supervisorStatePreFlChecksPassed;} bool supervisorIsArmed(void){return armed;} bool supervisorIsCrashed(void){return crashed;} bool supervisorRequestArming(bool a){if(!a){armed=false;if(supervisorState==supervisorStateArming)supervisorState=supervisorStateReadyToFly;return true;}if(!supervisorCanArm()&&supervisorState!=supervisorStateArming)return false;armed=true;supervisorState=supervisorStateArming;return true;} bool supervisorRequestCrashRecovery(bool r){if(supervisorState==supervisorStateExceptFreeFall)return false;crashed=!r;return true;} bool supervisorAreMotorsAllowedToRun(void){return supervisorState==supervisorStateArming||supervisorCanFly();}
bool isFlyingCheck(const uint32_t m[4],uint32_t idle,uint32_t t){int i;if(m)for(i=0;i<4;i++)if(m[i]>idle){flightTick=t;flightSeen=true;}return flightSeen&&(uint32_t)(t-flightTick)<IS_FLYING_HYSTERESIS_THRESHOLD;} bool isTumbledCheck(float x,float y,float z,float cg,float ff,float tz,float uz,uint32_t mt,uint32_t mu,bool en,uint32_t t,bool *free){float n=sqrtf(x*x+y*y+z*z);bool f=fabsf(x)<ff&&fabsf(y)<ff&&fabsf(z)<ff,tilt=z<tz,up=z<uz;if(free)*free=f;if(cg>0&&fabsf(n-1)>cg)crashed=true;if(f){tiltTick=0;return false;}if(!en||!tilt){tiltTick=0;return false;}if(!tiltTick){tiltTick=t;tiltUpside=up;return false;}return (uint32_t)(t-tiltTick)>=(tiltUpside?mu:mt);} bool checkEmergencyStopWatchdog(uint32_t t,uint32_t n){return n==0||(uint32_t)(t-n)<=DEFAULT_EMERGENCY_STOP_WATCHDOG_TIMEOUT;} bool supervisorIsPreflightTimeout(SupervisorState s,uint32_t a,uint32_t t,uint32_t d){return s==supervisorStateReadyToFly&&a&&(uint32_t)(t-a)>=d;} bool supervisorIsLandingTimeout(uint32_t a,uint32_t t,uint32_t d){return a&&(uint32_t)(t-a)>=d;} uint32_t updateAndPopulateConditions(bool a,bool b,bool c){if(a||b)supervisorConditionBits|=SUPERVISOR_CB_EMERGENCY_STOP;if(c)supervisorConditionBits|=SUPERVISOR_CB_COMMANDER_WDT_TIMEOUT;return supervisorConditionBits;}
void supervisorOverrideSetpoint(Setpoint *s,uint32_t b,SupervisorState st){if(!s)return;if(st==supervisorStateWarningLevelOut){s->mode.x=s->mode.y=modeDisable;s->mode.roll=s->mode.pitch=modeAbs;s->attitude.roll=s->attitude.pitch=0;s->mode.yaw=modeVelocity;s->attitudeRate.yaw=0;}else if(st!=supervisorStateArming&&st!=supervisorStateReadyToFly&&st!=supervisorStateFlying&&st!=supervisorStateLanded)memset(s,0,sizeof(*s));if(b&(SUPERVISOR_CB_EMERGENCY_STOP|SUPERVISOR_CB_COMMANDER_WDT_TIMEOUT|SUPERVISOR_CB_IS_TUMBLED|SUPERVISOR_CB_FREE_FALL|SUPERVISOR_CB_MOTORS_NOT_RESPONDING))s->thrust=0;}
bool isRPMatArmingValid(const int32_t r[4],int32_t lo,int32_t hi){int i;if(!r)return false;for(i=0;i<4;i++)if(r[i]<lo||r[i]>hi)return false;return true;} bool isMotorsNotResponding(const int32_t r[4],int32_t th,uint32_t d,bool can,uint32_t t){int i;bool bad=true;if(!can){rpmTick=0;return false;}for(i=0;i<4;i++)if(r&&r[i]>=th)bad=false;if(!bad){rpmTick=0;return false;}if(!rpmTick)rpmTick=t;return (uint32_t)(t-rpmTick)>=d;} void supervisorSetSensorData(const SensorData *s){if(s)supervisorSensors=*s;} void supervisorSetMotorRatios(const uint32_t r[4],uint32_t i){if(r)memcpy(ratios,r,sizeof(ratios));idleThrust=i;} void supervisorSetMotorRPMs(const int32_t r[4]){if(r)memcpy(rpms,r,sizeof(rpms));} void supervisorConfigureSafety(float a,float b,float c,float d,uint32_t e,uint32_t f,bool g){crashGs=a;freeFallGs=b;tiltAccZ=c;upsideAccZ=d;tiltTimeout=e;upsideTimeout=f;tumbleEnabled=g;} void supervisorConfigureArming(bool a,uint32_t d){autoArm=a;spinTimeout=d;} void supervisorUpdate(uint32_t step){bool ff,tu;if(!RATE_DO_EXECUTE(RATE_SUPERVISOR,step))return;nowTick=step;tu=isTumbledCheck(supervisorSensors.acc.x,supervisorSensors.acc.y,supervisorSensors.acc.z,crashGs,freeFallGs,tiltAccZ,upsideAccZ,tiltTimeout,upsideTimeout,tumbleEnabled,nowTick,&ff);if(ff)supervisorConditionBits|=SUPERVISOR_CB_FREE_FALL;if(tu)supervisorConditionBits|=SUPERVISOR_CB_IS_TUMBLED;if(crashed)supervisorConditionBits|=SUPERVISOR_CB_CRASHED;if(supervisorState==supervisorStateArming){if(spinTimeout&&spinTick==0)spinTick=nowTick;else if(spinTick&&(uint32_t)(nowTick-spinTick)>=spinTimeout)supervisorConditionBits|=SUPERVISOR_CB_SPINUP_TIMEOUT;}else{spinTick=0;supervisorConditionBits&=~SUPERVISOR_CB_SPINUP_TIMEOUT;}}
uint16_t supervisorGetInfoBitfield(void){uint16_t b=0;if(supervisorCanArm())b|=1;if(armed)b|=2;if(autoArm)b|=4;if(supervisorCanFly())b|=8;if(isFlyingCheck(ratios,idleThrust,nowTick))b|=16;if(supervisorConditionBits&SUPERVISOR_CB_IS_TUMBLED)b|=32;if(!supervisorCanFly())b|=64;if(crashed)b|=128;supervisorLog.info=supervisorConditionBits;supervisorLog.accNorm=sqrtf(supervisorSensors.acc.x*supervisorSensors.acc.x+supervisorSensors.acc.y*supervisorSensors.acc.y+supervisorSensors.acc.z*supervisorSensors.acc.z);return b;}
bool estimatorEnqueue(const EstimatorMeasurement *m){if(!m||ec>=16)return false;ef[eh]=*m;eh=(eh+1)%16;ec++;return true;} bool estimatorDequeue(EstimatorMeasurement *m){if(!m||ec==0)return false;*m=ef[et];et=(et+1)%16;ec--;return true;} void estimatorComplementary(uint32_t s){EstimatorMeasurement m;while(estimatorDequeue(&m)){if(m.type==MeasurementTypeGyroscope)gyro=(Axis3Log){m.data[0],m.data[1],m.data[2]};else if(m.type==MeasurementTypeAcceleration)acc=(Axis3Log){m.data[0],m.data[1],m.data[2]};else if(m.type==MeasurementTypeBarometer)baro=(BaroLog){m.data[2],m.data[1],m.data[0]};}if(RATE_DO_EXECUTE(RATE_250_HZ,s)){sensfusion6UpdateQ(gyro.x,gyro.y,gyro.z,acc.x,acc.y,acc.z,.004f);sensfusion6GetEulerRPY(&stateEstimate.roll,&stateEstimate.pitch,&stateEstimate.yaw);stateEstimate.qw=qw;stateEstimate.qx=qx;stateEstimate.qy=qy;stateEstimate.qz=qz;}}
bool commanderSetSetpoint(const Setpoint *s,int p){if(!s)return false;if(p==COMMANDER_PRIORITY_DISABLE||p>=activePriority){activeSetpoint=*s;activePriority=p;cmdTick=nowTick;return true;}return false;} void commanderRelaxPriority(void){activePriority=COMMANDER_PRIORITY_LOWEST;} uint32_t commanderGetInactivityTime(void){return nowTick-cmdTick;} int commanderGetActivePriority(void){return activePriority;}
static uint32_t quatCompress(Quaternion q){int32_t a=limitf(q.x,-1,1)*511,b=limitf(q.y,-1,1)*511,c=limitf(q.z,-1,1)*511;return ((uint32_t)(a&1023)<<20)|((uint32_t)(b&1023)<<10)|(uint32_t)(c&1023);} void compressState(const State *s,const SensorData *d,CompressedState *o){if(!s||!d||!o)return;for(int i=0;i<3;i++){float *p=(float*)&s->position;float *v=(float*)&s->velocity;float *a=(float*)&d->acc;float *g=(float*)&d->gyro;o->position_mm[i]=lroundf(p[i]*1000);o->velocity_mms[i]=lroundf(v[i]*1000);o->acceleration_mms2[i]=lroundf((i==2?(a[i]+1):a[i])*9810);o->gyro_millirad_s[i]=g[i]*RAD*1000*(i==1?-1:1);}o->quatCompressed=quatCompress(s->attitudeQuaternion);}
void stabilizerInit(void){static bool done;if(done)return;done=true;sensfusion6Init();attitudeControllerInit(.002f);supervisorInit();crtpInit();stabilizerReady=true;} void stabilizerTask(void){if(!stabilizerReady)stabilizerInit();nowTick++;estimatorComplementary(nowTick);supervisorUpdate(nowTick);if(highLevelPending){commanderSetSetpoint(&highLevelSetpoint,COMMANDER_PRIORITY_HIGHLEVEL);highLevelPending=false;}} bool stabilizerSubmitHighLevelSetpoint(const Setpoint *s){if(!s)return false;highLevelSetpoint=*s;highLevelPending=true;return true;} bool rateSupervisorValidate(uint32_t r){return r>=997&&r<=1003;} void rateSupervisorTask(void){}
void healthRequestPropTest(void){propReq=true;} void healthRequestBatteryTest(void){batReq=true;} bool healthShallWeRunTest(void){if(propReq){propReq=false;healthTestState=configureAcc;return true;}if(batReq){batReq=false;healthTestState=testBattery;return true;}return healthTestState!=testDone;} bool evaluatePropTest(float lo,float hi,float v,uint8_t m){bool ok=hi==0||(v>=lo&&v<=hi);if(ok&&m<8)motorPass|=(uint8_t)(1U<<m);return ok;} float variance(const float *b,int n){double sum=0,sq=0;if(!b||n<=0)return 0;for(int i=0;i<n;i++){sum+=b[i];sq+=(double)b[i]*b[i];}return (float)(sq-sum*sum/n);}
void healthRunTests(const SensorData *d){static float buf[100];static int n;static uint8_t tm;static float idle,minv;static uint32_t bt;if(!d)return;if(healthTestState==configureAcc){motorPass=0;n=0;tm=0;healthTestState=measureNoiseFloor;}else if(healthTestState==measureNoiseFloor){if(n<100)buf[n++]=d->acc.z;else healthTestState=measureProp;}else if(healthTestState==measureProp){evaluatePropTest(0,0,variance(buf,n),tm);healthLog.motorTestCount++;if(++tm>=4)healthTestState=testDone;}else if(healthTestState==testBattery){if(bt==0){idle=minv=d->baroPressure;bt=1;}else if(bt<50){if(d->baroPressure<minv)minv=d->baroPressure;bt++;}else healthTestState=evaluateBatResult;}else if(healthTestState==evaluateBatResult){batterySag=idle-minv;batteryPass=batterySag<=0;healthTestState=testDone;}}
typedef struct {CrtpPacket q[CRTP_TX_QUEUE_SIZE];uint16_t h,t,n;} TxQ; static TxQ txq; static CrtpPacket rxq[CRTP_NBR_OF_PORTS][CRTP_RX_QUEUE_SIZE]; static uint8_t rh[16],rt[16],rn[16]; static bool qcreated[16]; static CrtpPortCallback callbacks[16]; static CrtpLink *link;
static bool nopSend(CrtpPacket *p){(void)p;return false;} static bool nopRecv(CrtpPacket *p){(void)p;return false;} static bool nopConn(void){return true;} static void nopEnable(bool e){(void)e;} static void nopReset(void){} static CrtpLink nop={nopSend,nopRecv,nopConn,nopEnable,nopReset};
void crtpInit(void){static bool done;if(done)return;done=true;memset(&txq,0,sizeof(txq));memset(qcreated,0,sizeof(qcreated));memset(callbacks,0,sizeof(callbacks));link=&nop;} void crtpInitTaskQueue(uint8_t p){if(p<CRTP_NBR_OF_PORTS&&!qcreated[p]){qcreated[p]=true;rh[p]=rt[p]=rn[p]=0;}} bool crtpSendPacket(const CrtpPacket *p){if(!p||txq.n>=CRTP_TX_QUEUE_SIZE)return false;txq.q[txq.h]=*p;txq.h=(txq.h+1)%CRTP_TX_QUEUE_SIZE;txq.n++;return true;} bool crtpSendPacketBlock(const CrtpPacket *p){return crtpSendPacket(p);} bool crtpReceivePacket(uint8_t p,CrtpPacket *x){if(p>=CRTP_NBR_OF_PORTS||!x||!rn[p])return false;*x=rxq[p][rt[p]];rt[p]=(rt[p]+1)%CRTP_RX_QUEUE_SIZE;rn[p]--;return true;} bool crtpReceivePacketBlock(uint8_t p,CrtpPacket *x){return crtpReceivePacket(p,x);} bool crtpReceivePacketWait(uint8_t p,CrtpPacket *x,uint32_t w){(void)w;return crtpReceivePacket(p,x);} void crtpRxTask(void){CrtpPacket p;if(!link||!link->receivePacket||!link->receivePacket(&p))return;if(p.port<CRTP_NBR_OF_PORTS&&qcreated[p.port]&&rn[p.port]<CRTP_RX_QUEUE_SIZE){rxq[p.port][rh[p.port]]=p;rh[p.port]=(rh[p.port]+1)%CRTP_RX_QUEUE_SIZE;rn[p.port]++;}if(p.port<CRTP_NBR_OF_PORTS&&callbacks[p.port])callbacks[p.port](&p);} void crtpTxTask(void){if(txq.n&&link&&link->sendPacket&&link->sendPacket(&txq.q[txq.t])){txq.t=(txq.t+1)%CRTP_TX_QUEUE_SIZE;txq.n--;}} void crtpSetLink(CrtpLink *l){if(!l)l=&nop;if(link&&link->setEnable)link->setEnable(false);link=l;if(link->setEnable)link->setEnable(true);} void crtpReset(void){txq.h=txq.t=txq.n=0;if(link&&link->reset)link->reset();} bool crtpIsConnected(void){return !link||!link->isConnected||link->isConnected();} uint32_t crtpGetFreeTxQueuePackets(void){return CRTP_TX_QUEUE_SIZE-txq.n;} void crtpRegisterPortCB(uint8_t p,CrtpPortCallback f){if(p<CRTP_NBR_OF_PORTS)callbacks[p]=f;} void updateStats(void){}
uint8_t deckDiscovery(DeckInfo *d,uint8_t c){(void)d;(void)c;return 0;}