#include "6_generated_code.h"
#include <limits.h>
#include <math.h>
#include <string.h>
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

float qw = 1.0f, qx = 0.0f, qy = 0.0f, qz = 0.0f;
float gravityX = 0.0f, gravityY = 0.0f, gravityZ = 1.0f;
float integralFBx = 0.0f, integralFBy = 0.0f, integralFBz = 0.0f;
float twoKp = 0.8f, twoKi = 0.002f, beta = 0.01f, baseZacc = 0.0f;
bool sensfusion6IsInit = false, sensfusion6IsCalibrated = false;
PidObject pidRoll, pidPitch, pidYaw, pidRollRate, pidPitchRate, pidYawRate;
bool thrustLocked = false, commanderModeSet = false;
SupervisorState supervisorState = supervisorStateLocked;
uint32_t supervisorConditionBits = 0;
StateEstimateLog stateEstimate;
Axis3Log gyro, acc;
BaroLog baro;
MotorLog motor;
Sensfusion6Log sensfusion6Log;
SupervisorLog supervisorLog;
HealthLog healthLog;
TestState healthTestState = testDone;
uint8_t motorPass = 0, batteryPass = 0;
float batterySag = 0.0f;

static bool attitudeInitDone;
static uint32_t flightTick;
static bool flightSeen;
static SensorData supSensor;
static uint32_t supRatios[4], supIdle, supSpinTick;
static int32_t supRpm[4];
static float crashGs, freeFall, tiltZ, upsideZ;
static uint32_t tiltTime, upsideTime, spinTimeout;
static bool tumbleEnabled, autoArm;
static bool propReq, batReq;
static Setpoint activeSp, pendingHighLevel;
static int activePr = COMMANDER_PRIORITY_LOWEST;
static uint32_t activeTick;
static bool hasPendingHighLevel;

static float clampf_local(float value, float low, float high) { return value < low ? low : (value > high ? high : value); }
static uint16_t clamp_u16_from_float(float value) { if (value <= 0.0f) return 0; if (value >= 65535.0f) return 65535U; return (uint16_t)(value + 0.5f); }
static void updateSensfusionLog(void) { sensfusion6Log.qw = qw; sensfusion6Log.qx = qx; sensfusion6Log.qy = qy; sensfusion6Log.qz = qz; sensfusion6Log.gravityX = gravityX; sensfusion6Log.gravityY = gravityY; sensfusion6Log.gravityZ = gravityZ; sensfusion6Log.accZbase = baseZacc; sensfusion6Log.isInit = sensfusion6IsInit; sensfusion6Log.isCalibrated = sensfusion6IsCalibrated; }

int16_t saturateSignedInt16(int32_t value) { if (value > INT16_MAX) return INT16_MAX; if (value < -INT16_MAX) return -INT16_MAX; return (int16_t)value; }
float capAngle(float angle_deg) { while (angle_deg > 180.0f) angle_deg -= 360.0f; while (angle_deg < -180.0f) angle_deg += 360.0f; return angle_deg; }
float invSqrt(float x) { if (x <= 0.0f) return 0.0f; union { float f; uint32_t i; } u; u.f = x; u.i = 0x5f3759dfU - (u.i >> 1); u.f = u.f * (1.5f - 0.5f * x * u.f * u.f); return u.f; }
void estimatedGravityDirection(float w, float x, float y, float z, float *gravX, float *gravY, float *gravZ) { if (gravX) *gravX = 2.0f * (x * z - w * y); if (gravY) *gravY = 2.0f * (w * x + y * z); if (gravZ) *gravZ = w * w - x * x - y * y + z * z; }
void sensfusion6Init(void) { if (sensfusion6IsInit) return; qw = 1.0f; qx = qy = qz = 0.0f; gravityX = gravityY = 0.0f; gravityZ = 1.0f; integralFBx = integralFBy = integralFBz = 0.0f; baseZacc = 0.0f; sensfusion6IsCalibrated = false; sensfusion6IsInit = true; updateSensfusionLog(); }
bool sensfusion6Test(void) { return sensfusion6IsInit; }
void sensfusion6UpdateQ(float gx, float gy, float gz, float ax, float ay, float az, float dt) { if (!sensfusion6IsInit) sensfusion6Init(); estimatedGravityDirection(qw, qx, qy, qz, &gravityX, &gravityY, &gravityZ); float norm = sqrtf(ax * ax + ay * ay + az * az); if (norm > 0.0f) { ax /= norm; ay /= norm; az /= norm; float ex = ay * gravityZ - az * gravityY; float ey = az * gravityX - ax * gravityZ; float ez = ax * gravityY - ay * gravityX; if (twoKi > 0.0f) { integralFBx += twoKi * ex * dt; integralFBy += twoKi * ey * dt; integralFBz += twoKi * ez * dt; gx += integralFBx; gy += integralFBy; gz += integralFBz; } else { integralFBx = integralFBy = integralFBz = 0.0f; } gx += twoKp * ex; gy += twoKp * ey; gz += twoKp * ez; if (!sensfusion6IsCalibrated) { baseZacc = ax * gravityX + ay * gravityY + az * gravityZ; sensfusion6IsCalibrated = true; } } gx *= (float)M_PI / 180.0f; gy *= (float)M_PI / 180.0f; gz *= (float)M_PI / 180.0f; float halfDt = 0.5f * dt; float w = qw, x = qx, y = qy, z = qz; qw += (-x * gx - y * gy - z * gz) * halfDt; qx += (w * gx + y * gz - z * gy) * halfDt; qy += (w * gy - x * gz + z * gx) * halfDt; qz += (w * gz + x * gy - y * gx) * halfDt; norm = invSqrt(qw * qw + qx * qx + qy * qy + qz * qz); if (norm > 0.0f) { qw *= norm; qx *= norm; qy *= norm; qz *= norm; } estimatedGravityDirection(qw, qx, qy, qz, &gravityX, &gravityY, &gravityZ); updateSensfusionLog(); }
void sensfusion6GetEulerRPY(float *roll_deg, float *pitch_deg, float *yaw_deg) { estimatedGravityDirection(qw, qx, qy, qz, &gravityX, &gravityY, &gravityZ); float gxv = clampf_local(gravityX, -1.0f, 1.0f); if (roll_deg) *roll_deg = atan2f(gravityY, gravityZ) * 180.0f / (float)M_PI; if (pitch_deg) *pitch_deg = asinf(-gxv) * 180.0f / (float)M_PI; if (yaw_deg) *yaw_deg = atan2f(2.0f * (qw * qz + qx * qy), 1.0f - 2.0f * (qy * qy + qz * qz)) * 180.0f / (float)M_PI; updateSensfusionLog(); }
void sensfusion6GetQuaternion(float *outQw, float *outQx, float *outQy, float *outQz) { if (outQw) *outQw = qw; if (outQx) *outQx = qx; if (outQy) *outQy = qy; if (outQz) *outQz = qz; }
float sensfusion6GetAccZ(float ax, float ay, float az) { estimatedGravityDirection(qw, qx, qy, qz, &gravityX, &gravityY, &gravityZ); return ax * gravityX + ay * gravityY + az * gravityZ; }
float sensfusion6GetAccZWithoutGravity(float ax, float ay, float az) { return sensfusion6GetAccZ(ax, ay, az) - baseZacc; }

void powerDistributionLegacy(uint16_t thrust, int16_t roll, int16_t pitch, int16_t yaw, MotorPower *out) { if (!out) return; int32_t r = roll / 2, p = pitch / 2, t = thrust, y = yaw; out->m1 = t - r + p + y; out->m2 = t - r - p - y; out->m3 = t + r - p + y; out->m4 = t + r + p - y; }
void powerDistributionForceTorque(float thrustSi, float torqueX, float torqueY, float torqueZ, float armLength, float thrustToTorque, float motorForces[4]) { if (!motorForces) return; float arm = 0.707106781f * armLength; float thrustPart = 0.25f * thrustSi; float rollPart = arm != 0.0f ? 0.25f * torqueX / arm : 0.0f; float pitchPart = arm != 0.0f ? 0.25f * torqueY / arm : 0.0f; float yawPart = thrustToTorque != 0.0f ? 0.25f * torqueZ / thrustToTorque : 0.0f; motorForces[0] = fmaxf(0.0f, thrustPart - rollPart + pitchPart + yawPart); motorForces[1] = fmaxf(0.0f, thrustPart - rollPart - pitchPart - yawPart); motorForces[2] = fmaxf(0.0f, thrustPart + rollPart - pitchPart + yawPart); motorForces[3] = fmaxf(0.0f, thrustPart + rollPart + pitchPart - yawPart); }
void powerDistributionForce(const float normalizedForces[4], uint16_t motorPWMs[4]) { if (!normalizedForces || !motorPWMs) return; for (int i = 0; i < 4; i++) motorPWMs[i] = clamp_u16_from_float(clampf_local(normalizedForces[i], 0.0f, 1.0f) * 65535.0f); }
void powerDistribution(const ControlData *control, MotorPower *motorPower) { if (!control || !motorPower) return; if (control->controlMode == controlModeLegacy) { powerDistributionLegacy(control->thrust, control->roll, control->pitch, control->yaw, motorPower); } else if (control->controlMode == controlModeForceTorque) { float f[4]; powerDistributionForceTorque(control->thrustSi, control->torque.x, control->torque.y, control->torque.z, CRAZYFLIE_ARM_LENGTH_M, CRAZYFLIE_THRUST_TO_TORQUE, f); motorPower->m1 = (int32_t)(f[0] / CRAZYFLIE_MAX_MOTOR_FORCE_N * 65535.0f + 0.5f); motorPower->m2 = (int32_t)(f[1] / CRAZYFLIE_MAX_MOTOR_FORCE_N * 65535.0f + 0.5f); motorPower->m3 = (int32_t)(f[2] / CRAZYFLIE_MAX_MOTOR_FORCE_N * 65535.0f + 0.5f); motorPower->m4 = (int32_t)(f[3] / CRAZYFLIE_MAX_MOTOR_FORCE_N * 65535.0f + 0.5f); } else if (control->controlMode == controlModeForce) { uint16_t p[4]; powerDistributionForce(control->normalizedForces, p); motorPower->m1 = p[0]; motorPower->m2 = p[1]; motorPower->m3 = p[2]; motorPower->m4 = p[3]; } }
int32_t capMinThrust(int32_t value, int32_t idleThrust) { return value < idleThrust ? idleThrust : value; }
PowerCapResult powerDistributionCap(int32_t motors[4], int32_t maxAllowedThrust, int32_t idleThrust) { PowerCapResult result = { false, 0 }; if (!motors) return result; int32_t maxMotor = motors[0]; for (int i = 1; i < 4; i++) if (motors[i] > maxMotor) maxMotor = motors[i]; if (maxMotor > maxAllowedThrust) { result.isCapped = true; result.reduction = maxMotor - maxAllowedThrust; for (int i = 0; i < 4; i++) motors[i] = capMinThrust(motors[i] - result.reduction, idleThrust); } return result; }
float batteryCompensation(float supplyVoltage, float filteredOld, float alpha) { return filteredOld + alpha * (supplyVoltage - filteredOld); }
uint16_t motorsCompensateBatteryVoltage(uint16_t motorThrust, float nominalVoltage, float actualVoltage) { if (actualVoltage <= 0.0f) return motorThrust; return clamp_u16_from_float((float)motorThrust * nominalVoltage / actualVoltage); }

static void pidReset(PidObject *pid, float previousError) { if (!pid) return; pid->integral = 0.0f; pid->prevError = previousError; pid->output = 0.0f; pid->initialized = true; }
static int16_t pidStep(PidObject *pid, float actual, float desired) { if (!pid) return 0; float error = desired - actual; pid->integral += error * 0.002f; pid->output = pid->kp * error + pid->ki * pid->integral + pid->kd * (error - pid->prevError) + pid->kff * desired; pid->prevError = error; return saturateSignedInt16((int32_t)pid->output); }
void attitudeControllerInit(float updateDt) { (void)updateDt; if (attitudeInitDone) return; PidObject *pids[6] = { &pidRoll, &pidPitch, &pidYaw, &pidRollRate, &pidPitchRate, &pidYawRate }; for (int i = 0; i < 6; i++) { memset(pids[i], 0, sizeof(*pids[i])); pids[i]->kp = 1.0f; pids[i]->initialized = true; } attitudeInitDone = true; }
void attitudeControllerCorrectRatePID(float rollActual, float rollDesired, float pitchActual, float pitchDesired, float yawActual, float yawDesired) { pidRollRate.output = pidStep(&pidRollRate, rollActual, rollDesired); pidPitchRate.output = pidStep(&pidPitchRate, pitchActual, pitchDesired); pidYawRate.output = pidStep(&pidYawRate, yawActual, yawDesired); }
void attitudeControllerCorrectAttitudePID(float rollActual, float rollDesired, float pitchActual, float pitchDesired, float yawActual, float yawDesired) { pidRoll.output = pidStep(&pidRoll, rollActual, rollDesired); pidPitch.output = pidStep(&pidPitch, pitchActual, pitchDesired); pidYaw.output = pidStep(&pidYaw, yawActual, yawDesired); }
void attitudeControllerResetAllPID(float rollActual, float pitchActual, float yawActual) { pidReset(&pidRoll, rollActual); pidReset(&pidPitch, pitchActual); pidReset(&pidYaw, yawActual); pidReset(&pidRollRate, 0.0f); pidReset(&pidPitchRate, 0.0f); pidReset(&pidYawRate, 0.0f); }
void attitudeControllerResetRollAttitudePID(float rollActual) { pidReset(&pidRoll, rollActual); }
void attitudeControllerResetPitchAttitudePID(float pitchActual) { pidReset(&pidPitch, pitchActual); }
void attitudeControllerGetActuatorOutput(int16_t *roll, int16_t *pitch, int16_t *yaw) { if (roll) *roll = saturateSignedInt16((int32_t)pidRollRate.output); if (pitch) *pitch = saturateSignedInt16((int32_t)pidPitchRate.output); if (yaw) *yaw = saturateSignedInt16((int32_t)pidYawRate.output); }
uint16_t positionControllerUpdate(const Setpoint *setpoint, const State *state) { if (!setpoint || !state) return 0; float out = (float)setpoint->thrust + (setpoint->position.z - state->position.z) * 1000.0f + (setpoint->velocity.z - state->velocity.z) * 100.0f; return clamp_u16_from_float(out); }
void controllerPid(const SensorData *sensors, const Setpoint *setpoint, const State *state, ControlData *control, float yawMaxDelta, float attitudeUpdateDt) { static float desiredYaw; if (!sensors || !setpoint || !state || !control) return; memset(control, 0, sizeof(*control)); control->controlMode = controlModeLegacy; if (setpoint->thrust == 0U) { attitudeControllerResetAllPID(state->attitude.roll, state->attitude.pitch, state->attitude.yaw); desiredYaw = state->attitude.yaw; return; } float desiredRoll = setpoint->attitude.roll; float desiredPitch = setpoint->attitude.pitch; if (setpoint->mode.yaw == modeVelocity) desiredYaw += setpoint->attitudeRate.yaw * attitudeUpdateDt; else if (setpoint->mode.quat == modeAbs) { float ys = 2.0f * (setpoint->attitudeQuaternion.w * setpoint->attitudeQuaternion.z + setpoint->attitudeQuaternion.x * setpoint->attitudeQuaternion.y); float yc = 1.0f - 2.0f * (setpoint->attitudeQuaternion.y * setpoint->attitudeQuaternion.y + setpoint->attitudeQuaternion.z * setpoint->attitudeQuaternion.z); desiredYaw = atan2f(ys, yc) * 180.0f / (float)M_PI; } else desiredYaw = setpoint->attitude.yaw; if (yawMaxDelta != 0.0f) { float delta = capAngle(desiredYaw - state->attitude.yaw); delta = clampf_local(delta, -yawMaxDelta, yawMaxDelta); desiredYaw = state->attitude.yaw + delta; } if (setpoint->mode.roll == modeVelocity) { desiredRoll = setpoint->attitudeRate.roll; attitudeControllerResetRollAttitudePID(state->attitude.roll); } if (setpoint->mode.pitch == modeVelocity) { desiredPitch = setpoint->attitudeRate.pitch; attitudeControllerResetPitchAttitudePID(state->attitude.pitch); } attitudeControllerCorrectAttitudePID(state->attitude.roll, desiredRoll, state->attitude.pitch, desiredPitch, state->attitude.yaw, desiredYaw); attitudeControllerCorrectRatePID(sensors->gyro.x, pidRoll.output, -sensors->gyro.y, pidPitch.output, sensors->gyro.z, pidYaw.output); control->roll = saturateSignedInt16((int32_t)pidRollRate.output); control->pitch = saturateSignedInt16((int32_t)pidPitchRate.output); control->yaw = saturateSignedInt16(-(int32_t)pidYawRate.output); control->thrust = setpoint->mode.z == modeDisable ? setpoint->thrust : positionControllerUpdate(setpoint, state); }

void rotateYaw(float roll, float pitch, float yaw_deg, float *rollPrime, float *pitchPrime) { float a = yaw_deg * (float)M_PI / 180.0f; float c = cosf(a), s = sinf(a); if (rollPrime) *rollPrime = roll * c - pitch * s; if (pitchPrime) *pitchPrime = roll * s + pitch * c; }
void crtpCommanderRpytDecodeSetpoint(const CommanderCrtpLegacyValues *values, Setpoint *setpoint, bool altHoldMode, bool posHoldMode, bool posSetMode, StabilizationType stabilizationModeRoll, StabilizationType stabilizationModePitch, StabilizationType stabilizationModeYaw, YawMode yawMode) { if (!values || !setpoint) return; memset(setpoint, 0, sizeof(*setpoint)); if (values->thrust == 0U) thrustLocked = false; if (altHoldMode) { setpoint->mode.z = modeVelocity; setpoint->thrust = 0; setpoint->velocity.z = ((float)values->thrust - 32767.0f) / 32767.0f; if (!commanderModeSet) commanderModeSet = true; } else { if (commanderModeSet) commanderModeSet = false; if (thrustLocked || values->thrust < MIN_THRUST) setpoint->thrust = 0; else setpoint->thrust = values->thrust > MAX_THRUST ? MAX_THRUST : values->thrust; } if (posHoldMode) { setpoint->mode.x = modeVelocity; setpoint->mode.y = modeVelocity; setpoint->mode.roll = modeDisable; setpoint->mode.pitch = modeDisable; setpoint->velocity.x = values->pitch / 30.0f; setpoint->velocity.y = values->roll / 30.0f; setpoint->attitude.roll = 0.0f; setpoint->attitude.pitch = 0.0f; } else if (posSetMode && values->thrust != 0U) { setpoint->mode.x = modeAbs; setpoint->mode.y = modeAbs; setpoint->mode.z = modeAbs; setpoint->mode.roll = modeDisable; setpoint->mode.pitch = modeDisable; setpoint->mode.yaw = modeAbs; setpoint->position.x = -values->pitch; setpoint->position.y = values->roll; setpoint->position.z = values->thrust / 1000.0f; setpoint->attitude.yaw = values->yaw; setpoint->thrust = 0; } else { float roll = values->roll, pitch = values->pitch; if (yawMode == PLUSMODE) rotateYaw(values->roll, values->pitch, 45.0f, &roll, &pitch); setpoint->mode.roll = stabilizationModeRoll == RATE ? modeVelocity : modeAbs; setpoint->mode.pitch = stabilizationModePitch == RATE ? modeVelocity : modeAbs; setpoint->mode.yaw = stabilizationModeYaw == RATE ? modeVelocity : modeAbs; if (stabilizationModeRoll == RATE) setpoint->attitudeRate.roll = roll; else setpoint->attitude.roll = roll; if (stabilizationModePitch == RATE) setpoint->attitudeRate.pitch = pitch; else setpoint->attitude.pitch = pitch; if (stabilizationModeYaw == RATE) setpoint->attitudeRate.yaw = -values->yaw; else setpoint->attitude.yaw = values->yaw; } }

static bool stateCanFly(SupervisorState state) { return state == supervisorStateReadyToFly || state == supervisorStateFlying || state == supervisorStateWarningLevelOut || state == supervisorStateLanded; }
void supervisorInit(void) { supervisorState = supervisorStateLocked; supervisorConditionBits = 0; flightTick = 0; flightSeen = false; supSpinTick = 0; memset(&supSensor, 0, sizeof(supSensor)); memset(supRatios, 0, sizeof(supRatios)); memset(supRpm, 0, sizeof(supRpm)); }
bool supervisorCanFly(void) { return stateCanFly(supervisorState); }
bool supervisorCanArm(void) { return supervisorState == supervisorStatePreFlChecksPassed; }
bool supervisorIsArmed(void) { return (supervisorConditionBits & SUPERVISOR_CB_ARMED) != 0U; }
bool supervisorIsCrashed(void) { return (supervisorConditionBits & SUPERVISOR_CB_CRASHED) != 0U || supervisorState == supervisorStateCrashed; }
bool supervisorRequestArming(bool doArm) { if (doArm) { if (!supervisorCanArm() && !supervisorIsArmed()) return false; supervisorConditionBits |= SUPERVISOR_CB_ARMED; supervisorState = supervisorStateArming; if (supSpinTick == 0U) supSpinTick = 1U; return true; } supervisorConditionBits &= ~SUPERVISOR_CB_ARMED; if (supervisorState == supervisorStateArming) supervisorState = supervisorStateReadyToFly; supSpinTick = 0; return true; }
bool supervisorRequestCrashRecovery(bool doRecovery) { if (doRecovery) { if ((supervisorConditionBits & SUPERVISOR_CB_IS_TUMBLED) != 0U) return false; supervisorConditionBits &= ~SUPERVISOR_CB_CRASHED; if (supervisorState == supervisorStateCrashed) supervisorState = supervisorStateLocked; return true; } supervisorConditionBits |= SUPERVISOR_CB_CRASHED; supervisorState = supervisorStateCrashed; return true; }
bool supervisorAreMotorsAllowedToRun(void) { return supervisorState == supervisorStateArming || stateCanFly(supervisorState); }
uint16_t supervisorGetInfoBitfield(void) { uint16_t bits = 0; if (supervisorCanArm()) bits |= (1U << 0); if (supervisorIsArmed()) bits |= (1U << 1); if (autoArm) bits |= (1U << 2); if (supervisorCanFly()) bits |= (1U << 3); if (supervisorConditionBits & SUPERVISOR_CB_IS_FLYING) bits |= (1U << 4); if (supervisorConditionBits & SUPERVISOR_CB_IS_TUMBLED) bits |= (1U << 5); if (!supervisorIsArmed()) bits |= (1U << 6); if (supervisorIsCrashed()) bits |= (1U << 7); if (supervisorConditionBits & SUPERVISOR_CB_DECK_FAULT) bits |= (1U << 11); return bits; }
bool isFlyingCheck(const uint32_t motorRatios[4], uint32_t idleThrust, uint32_t currentTick) { if (motorRatios) { for (int i = 0; i < 4; i++) { if (motorRatios[i] > idleThrust) { flightTick = currentTick; flightSeen = true; break; } } } return flightSeen && (uint32_t)(currentTick - flightTick) < IS_FLYING_HYSTERESIS_THRESHOLD; }
bool isTumbledCheck(float accX, float accY, float accZ, float crashDetectionGs, float freeFallThreshold, float acceptedTiltAccZ, float acceptedUpsideDownAccZ, uint32_t maxTiltTime, uint32_t maxUpsideDownTime, bool tumbleCheckEnabled, uint32_t currentTick, bool *isFreeFalling) { static uint32_t tiltStart; if (isFreeFalling) *isFreeFalling = false; float norm = sqrtf(accX * accX + accY * accY + accZ * accZ); if (crashDetectionGs > 0.0f && fabsf(norm - 1.0f) > crashDetectionGs) supervisorConditionBits |= SUPERVISOR_CB_CRASHED; if (fabsf(accX) < freeFallThreshold && fabsf(accY) < freeFallThreshold && fabsf(accZ) < freeFallThreshold) { if (isFreeFalling) *isFreeFalling = true; supervisorConditionBits |= SUPERVISOR_CB_FREE_FALL; tiltStart = 0; return false; } if (!tumbleCheckEnabled) return false; uint32_t limit = 0; if (accZ < acceptedUpsideDownAccZ) limit = maxUpsideDownTime; else if (accZ < acceptedTiltAccZ) limit = maxTiltTime; else { tiltStart = 0; return false; } if (tiltStart == 0U) tiltStart = currentTick == 0U ? 1U : currentTick; return (uint32_t)(currentTick - tiltStart) >= limit; }
bool checkEmergencyStopWatchdog(uint32_t currentTick, uint32_t lastNotificationTick) { return lastNotificationTick == 0U || (uint32_t)(currentTick - lastNotificationTick) <= DEFAULT_EMERGENCY_STOP_WATCHDOG_TIMEOUT; }
bool supervisorIsPreflightTimeout(SupervisorState state, uint32_t latestArmingTick, uint32_t currentTick, uint32_t preflightTimeoutDuration) { return state == supervisorStateReadyToFly && latestArmingTick != 0U && (uint32_t)(currentTick - latestArmingTick) >= preflightTimeoutDuration; }
bool supervisorIsLandingTimeout(uint32_t latestLandingTick, uint32_t currentTick, uint32_t landingTimeoutDuration) { return latestLandingTick != 0U && (uint32_t)(currentTick - latestLandingTick) >= landingTimeoutDuration; }
uint32_t updateAndPopulateConditions(bool crtpEmergencyStop, bool paramEmergencyStop, bool emergencyStopWatchdogFailed) { if (crtpEmergencyStop || paramEmergencyStop) supervisorConditionBits |= SUPERVISOR_CB_EMERGENCY_STOP; else supervisorConditionBits &= ~SUPERVISOR_CB_EMERGENCY_STOP; if (emergencyStopWatchdogFailed) supervisorConditionBits |= SUPERVISOR_CB_COMMANDER_WDT_TIMEOUT; return supervisorConditionBits; }
void supervisorOverrideSetpoint(Setpoint *setpoint, uint32_t conditionBits, SupervisorState state) { if (!setpoint) return; if (conditionBits & (SUPERVISOR_CB_EMERGENCY_STOP | SUPERVISOR_CB_CRASHED | SUPERVISOR_CB_IS_TUMBLED | SUPERVISOR_CB_FREE_FALL | SUPERVISOR_CB_MOTORS_NOT_RESPONDING)) { memset(setpoint, 0, sizeof(*setpoint)); return; } if (state == supervisorStateWarningLevelOut) { setpoint->mode.x = modeDisable; setpoint->mode.y = modeDisable; setpoint->mode.roll = modeAbs; setpoint->mode.pitch = modeAbs; setpoint->mode.yaw = modeVelocity; setpoint->attitude.roll = 0.0f; setpoint->attitude.pitch = 0.0f; setpoint->attitudeRate.yaw = 0.0f; } else if (!(state == supervisorStateArming || state == supervisorStateReadyToFly || state == supervisorStateFlying || state == supervisorStateLanded)) { memset(setpoint, 0, sizeof(*setpoint)); } }
bool isRPMatArmingValid(const int32_t motorRPMs[4], int32_t rpmCheckMin, int32_t rpmCheckMax) { if (!motorRPMs) return false; for (int i = 0; i < 4; i++) if (motorRPMs[i] < rpmCheckMin || motorRPMs[i] > rpmCheckMax) return false; return true; }
bool isMotorsNotResponding(const int32_t motorRPMs[4], int32_t rpmThreshold, uint32_t rpmCheckDurationMs, bool canFly, uint32_t currentTick) { static uint32_t startTick; if (!canFly) { startTick = 0; return false; } bool allBad = true; for (int i = 0; i < 4; i++) if (motorRPMs && motorRPMs[i] >= rpmThreshold) allBad = false; if (!allBad) { startTick = 0; return false; } if (startTick == 0U) startTick = currentTick == 0U ? 1U : currentTick; return (uint32_t)(currentTick - startTick) >= rpmCheckDurationMs; }
void supervisorSetSensorData(const SensorData *sensors) { if (sensors) supSensor = *sensors; }
void supervisorSetMotorRatios(const uint32_t motorRatios[4], uint32_t idleThrust) { if (motorRatios) memcpy(supRatios, motorRatios, sizeof(supRatios)); supIdle = idleThrust; }
void supervisorSetMotorRPMs(const int32_t motorRPMs[4]) { if (motorRPMs) memcpy(supRpm, motorRPMs, sizeof(supRpm)); }
void supervisorConfigureSafety(float crashDetectionGs, float freeFallThreshold, float acceptedTiltAccZ, float acceptedUpsideDownAccZ, uint32_t maxTiltTime, uint32_t maxUpsideDownTime, bool tumbleCheckEnabled) { crashGs = crashDetectionGs; freeFall = freeFallThreshold; tiltZ = acceptedTiltAccZ; upsideZ = acceptedUpsideDownAccZ; tiltTime = maxTiltTime; upsideTime = maxUpsideDownTime; tumbleEnabled = tumbleCheckEnabled; }
void supervisorConfigureArming(bool autoArming, uint32_t spinupTimeoutDurationMs) { autoArm = autoArming; spinTimeout = spinupTimeoutDurationMs; }
void supervisorUpdate(uint32_t stabilizerStep) { if (!RATE_DO_EXECUTE(RATE_SUPERVISOR, stabilizerStep)) return; bool free = false; if (isFlyingCheck(supRatios, supIdle, stabilizerStep)) supervisorConditionBits |= SUPERVISOR_CB_IS_FLYING; else supervisorConditionBits &= ~SUPERVISOR_CB_IS_FLYING; if (isTumbledCheck(supSensor.acc.x, supSensor.acc.y, supSensor.acc.z, crashGs, freeFall, tiltZ, upsideZ, tiltTime, upsideTime, tumbleEnabled, stabilizerStep, &free)) supervisorConditionBits |= SUPERVISOR_CB_IS_TUMBLED; if (free) supervisorState = supervisorStateExceptFreeFall; if (supervisorState == supervisorStateArming && spinTimeout != 0U) { if (supSpinTick == 0U) supSpinTick = stabilizerStep == 0U ? 1U : stabilizerStep; if ((uint32_t)(stabilizerStep - supSpinTick) >= spinTimeout) supervisorConditionBits |= SUPERVISOR_CB_SPINUP_TIMEOUT; } else { supSpinTick = 0; supervisorConditionBits &= ~SUPERVISOR_CB_SPINUP_TIMEOUT; } supervisorLog.info = supervisorGetInfoBitfield(); supervisorLog.accNorm = sqrtf(supSensor.acc.x * supSensor.acc.x + supSensor.acc.y * supSensor.acc.y + supSensor.acc.z * supSensor.acc.z); }

static EstimatorMeasurement eq[16];
static unsigned eh, et, ec;
bool estimatorEnqueue(const EstimatorMeasurement *measurement) { if (!measurement || ec >= 16U) return false; eq[et] = *measurement; et = (et + 1U) % 16U; ec++; return true; }
bool estimatorDequeue(EstimatorMeasurement *measurement) { if (!measurement || ec == 0U) return false; *measurement = eq[eh]; eh = (eh + 1U) % 16U; ec--; return true; }
void estimatorComplementary(uint32_t stabilizerStep) { EstimatorMeasurement m; while (estimatorDequeue(&m)) { if (m.type == MeasurementTypeGyroscope) { gyro.x = m.data[0]; gyro.y = m.data[1]; gyro.z = m.data[2]; } else if (m.type == MeasurementTypeAcceleration) { acc.x = m.data[0]; acc.y = m.data[1]; acc.z = m.data[2]; } else if (m.type == MeasurementTypeBarometer) { baro.pressure = m.data[0]; baro.temp = m.data[1]; baro.asl = m.data[2]; } } if (RATE_DO_EXECUTE(RATE_250_HZ, stabilizerStep)) { sensfusion6UpdateQ(gyro.x, gyro.y, gyro.z, acc.x, acc.y, acc.z, 1.0f / (float)SENSFUSION_RATE_HZ); sensfusion6GetEulerRPY(&stateEstimate.roll, &stateEstimate.pitch, &stateEstimate.yaw); stateEstimate.qw = qw; stateEstimate.qx = qx; stateEstimate.qy = qy; stateEstimate.qz = qz; } }
bool commanderSetSetpoint(const Setpoint *setpoint, int priority) { if (!setpoint) return false; if (priority == COMMANDER_PRIORITY_DISABLE || priority >= activePr) { activeSp = *setpoint; activePr = priority; activeTick = setpoint->timestamp; return true; } return false; }
void commanderRelaxPriority(void) { activePr = COMMANDER_PRIORITY_LOWEST; }
uint32_t commanderGetInactivityTime(void) { return activeTick; }
int commanderGetActivePriority(void) { return activePr; }

void stabilizerInit(void) { static bool initialized; if (initialized) return; sensfusion6Init(); attitudeControllerInit(1.0f / (float)ATTITUDE_RATE_HZ); supervisorInit(); crtpInit(); initialized = true; }
void stabilizerTask(void) { if (hasPendingHighLevel) { commanderSetSetpoint(&pendingHighLevel, COMMANDER_PRIORITY_HIGHLEVEL); hasPendingHighLevel = false; } }
bool stabilizerSubmitHighLevelSetpoint(const Setpoint *setpoint) { if (!setpoint) return false; pendingHighLevel = *setpoint; hasPendingHighLevel = true; return true; }
static uint32_t quatcompress(float w, float x, float y, float z) { uint32_t a = ((uint32_t)((w + 1.0f) * 511.5f)) & 0x3ffU; uint32_t b = ((uint32_t)((x + 1.0f) * 511.5f)) & 0x3ffU; uint32_t c = ((uint32_t)((y + 1.0f) * 511.5f)) & 0x3ffU; uint32_t d = ((uint32_t)((z + 1.0f) * 0.5f)) & 0x1U; return a | (b << 10) | (c << 20) | (d << 30); }
void compressState(const State *state, const SensorData *sensors, CompressedState *output) { if (!state || !sensors || !output) return; output->position_mm[0] = (int32_t)(state->position.x * 1000.0f); output->position_mm[1] = (int32_t)(state->position.y * 1000.0f); output->position_mm[2] = (int32_t)(state->position.z * 1000.0f); output->velocity_mms[0] = (int32_t)(state->velocity.x * 1000.0f); output->velocity_mms[1] = (int32_t)(state->velocity.y * 1000.0f); output->velocity_mms[2] = (int32_t)(state->velocity.z * 1000.0f); output->acceleration_mms2[0] = (int32_t)(sensors->acc.x * 9810.0f); output->acceleration_mms2[1] = (int32_t)(sensors->acc.y * 9810.0f); output->acceleration_mms2[2] = (int32_t)((sensors->acc.z + 1.0f) * 9810.0f); output->gyro_millirad_s[0] = sensors->gyro.x * (float)M_PI / 180.0f * 1000.0f; output->gyro_millirad_s[1] = -sensors->gyro.y * (float)M_PI / 180.0f * 1000.0f; output->gyro_millirad_s[2] = sensors->gyro.z * (float)M_PI / 180.0f * 1000.0f; output->quatCompressed = quatcompress(state->attitudeQuaternion.w, state->attitudeQuaternion.x, state->attitudeQuaternion.y, state->attitudeQuaternion.z); }
bool rateSupervisorValidate(uint32_t measuredRate) { return measuredRate >= 997U && measuredRate <= 1003U; }
void rateSupervisorTask(void) { }

bool healthShallWeRunTest(void) { if (propReq) { propReq = false; healthTestState = configureAcc; motorPass = 0; healthLog.motorTestCount++; return true; } if (batReq) { batReq = false; healthTestState = testBattery; batteryPass = 0; batterySag = 0.0f; return true; } return healthTestState != testDone; }
void healthRequestPropTest(void) { propReq = true; }
void healthRequestBatteryTest(void) { batReq = true; }
void healthRunTests(const SensorData *sensorData) { (void)sensorData; if (healthTestState == configureAcc) healthTestState = measureNoiseFloor; else if (healthTestState == measureNoiseFloor) healthTestState = measureProp; else if (healthTestState == measureProp) healthTestState = evaluatePropResult; else if (healthTestState == evaluatePropResult) healthTestState = testDone; else if (healthTestState == testBattery) healthTestState = evaluateBatResult; else if (healthTestState == evaluateBatResult) { batteryPass = 1; healthTestState = testDone; } healthLog.motorPass = motorPass; healthLog.batteryPass = batteryPass; healthLog.batterySag = batterySag; }
bool evaluatePropTest(float lowThreshold, float highThreshold, float measuredValue, uint8_t motorIndex) { bool ok = highThreshold == 0.0f || (measuredValue >= lowThreshold && measuredValue <= highThreshold); if (ok && motorIndex < 4U) motorPass |= (uint8_t)(1U << motorIndex); return ok; }
float variance(const float *buffer, int length) { if (!buffer || length <= 0) return 0.0f; float sum = 0.0f, sumSq = 0.0f; for (int i = 0; i < length; i++) { sum += buffer[i]; sumSq += buffer[i] * buffer[i]; } return sumSq - (sum * sum / (float)length); }

static CrtpPacket tx[CRTP_TX_QUEUE_SIZE], rx[CRTP_NBR_OF_PORTS][CRTP_RX_QUEUE_SIZE];
static unsigned txh, txt, txc, rh[CRTP_NBR_OF_PORTS], rt[CRTP_NBR_OF_PORTS], rc[CRTP_NBR_OF_PORTS];
static bool rxCreated[CRTP_NBR_OF_PORTS];
static CrtpPortCallback cb[CRTP_NBR_OF_PORTS];
static CrtpLink *link;
static bool queuePush(CrtpPacket *queue, unsigned *tail, unsigned *count, unsigned capacity, const CrtpPacket *packet) { if (!packet || *count >= capacity) return false; queue[*tail] = *packet; *tail = (*tail + 1U) % capacity; (*count)++; return true; }
void crtpInit(void) { static bool initialized; if (initialized) return; txh = txt = txc = 0; memset(rh, 0, sizeof(rh)); memset(rt, 0, sizeof(rt)); memset(rc, 0, sizeof(rc)); memset(rxCreated, 0, sizeof(rxCreated)); memset(cb, 0, sizeof(cb)); initialized = true; }
void crtpInitTaskQueue(uint8_t port) { if (port >= CRTP_NBR_OF_PORTS) return; if (rxCreated[port]) { supervisorConditionBits |= SUPERVISOR_CB_DECK_FAULT; return; } rxCreated[port] = true; rh[port] = rt[port] = rc[port] = 0; }
bool crtpSendPacket(const CrtpPacket *packet) { return queuePush(tx, &txt, &txc, CRTP_TX_QUEUE_SIZE, packet); }
bool crtpSendPacketBlock(const CrtpPacket *packet) { return crtpSendPacket(packet); }
static bool takeRx(uint8_t port, CrtpPacket *packet) { if (port >= CRTP_NBR_OF_PORTS || !packet || rc[port] == 0U) return false; *packet = rx[port][rh[port]]; rh[port] = (rh[port] + 1U) % CRTP_RX_QUEUE_SIZE; rc[port]--; return true; }
bool crtpReceivePacket(uint8_t port, CrtpPacket *packet) { return takeRx(port, packet); }
bool crtpReceivePacketBlock(uint8_t port, CrtpPacket *packet) { return takeRx(port, packet); }
bool crtpReceivePacketWait(uint8_t port, CrtpPacket *packet, uint32_t wait_ms) { (void)wait_ms; return takeRx(port, packet); }
void crtpRxTask(void) { CrtpPacket packet; if (!link || !link->receivePacket) return; if (link->receivePacket(&packet)) { if (packet.port < CRTP_NBR_OF_PORTS && rxCreated[packet.port] && rc[packet.port] < CRTP_RX_QUEUE_SIZE) { rx[packet.port][rt[packet.port]] = packet; rt[packet.port] = (rt[packet.port] + 1U) % CRTP_RX_QUEUE_SIZE; rc[packet.port]++; } if (packet.port < CRTP_NBR_OF_PORTS && cb[packet.port]) cb[packet.port](&packet); } }
void crtpTxTask(void) { if (!link || !link->sendPacket || txc == 0U) return; if (link->sendPacket(&tx[txh])) { txh = (txh + 1U) % CRTP_TX_QUEUE_SIZE; txc--; } }
void crtpSetLink(CrtpLink *newLink) { if (link && link->setEnable) link->setEnable(false); link = newLink; if (link && link->setEnable) link->setEnable(true); }
void crtpReset(void) { txh = txt = txc = 0; if (link && link->reset) link->reset(); }
bool crtpIsConnected(void) { return link && link->isConnected ? link->isConnected() : true; }
uint32_t crtpGetFreeTxQueuePackets(void) { return CRTP_TX_QUEUE_SIZE - txc; }
void crtpRegisterPortCB(uint8_t port, CrtpPortCallback callback) { if (port < CRTP_NBR_OF_PORTS) cb[port] = callback; }
void updateStats(void) { }

uint8_t deckDiscovery(DeckInfo *decks, uint8_t capacity) { if (!decks || capacity == 0U) return 0; uint8_t count = 0; const uint8_t addrs[] = { 0x0aU, 0x0bU, 0x1cU, 0x1dU }; for (unsigned i = 0; i < sizeof(addrs) / sizeof(addrs[0]) && count < capacity; i++) { decks[count].foundByI2C = true; decks[count].foundByOneWire = false; decks[count].i2cAddress = addrs[i]; decks[count].oneWireRomId = 0; count++; } return count; }