#include "6_generated_code.h"
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define AXES 2
#define CHANNELS 4
#define NVM_BYTES 1024u
#define NVM_CAL_OFFSET 0u
#define NVM_CFG_OFFSET OS_NVM_CALIBRATION_SIZE_BYTES
#define NVM_PEC_OFFSET 512u
#define MAX_HZ 1000000u
#define STEPS_RA_HOUR 15000.0
#define STEPS_DEC_DEG 1000.0
#define PI 3.1415926535897932384626433832795
#define CAL_MAGIC 0x4f534341u
#define CFG_MAGIC 0x4f534346u
#define PEC_MAGIC 0x4f535045u

typedef struct { os_equatorial_coord_t star; os_motor_position_t motor; } sample_t;
typedef struct { bool initialized, enabled, forward; uint32_t frequency; int32_t position; double phase; } motor_t;
typedef struct { bool active; os_state_t final_state; int32_t target[AXES]; bool forward[AXES]; } motion_t;
typedef struct { uint32_t magic; os_calibration_t calib; float residual; uint32_t crc; } cal_record_t;
typedef struct { uint32_t magic; os_site_info_t site; os_equatorial_coord_t park; bool park_custom; os_track_rate_t rate; float factor; float guide_rate; bool pec_enabled; uint32_t crc; } cfg_record_t;
typedef struct { uint32_t magic; os_pec_table_t table; uint32_t crc; } pec_record_t;

static os_state_t g_state;
static motor_t g_motor[AXES];
static motion_t g_motion;
static os_site_info_t g_site;
static os_equatorial_coord_t g_park;
static bool g_park_custom, g_gps_locked, g_time_valid, g_tracking;
static uint32_t g_utc, g_tick_ms, g_guide_until;
static os_track_rate_t g_rate;
static float g_rate_factor, g_guide_rate, g_custom_speed;
static os_guide_pulse_t g_guide;
static os_calibration_t g_cal;
static float g_residual;
static bool g_residual_valid;
static os_align_mode_t g_align_mode;
static sample_t g_samples[OS_CALIBRATION_MAX_STARS];
static size_t g_sample_count;
static os_pec_table_t g_pec;
static bool g_pec_enabled, g_nvm_ready, g_limit[AXES], g_comm_ready[CHANNELS];
static uint8_t g_nvm[NVM_BYTES];
static char g_rx[CHANNELS][256], g_tx[CHANNELS][OS_MAX_REPLY_LENGTH * 4];
static size_t g_rx_head[CHANNELS], g_rx_tail[CHANNELS], g_tx_length[CHANNELS];
static char g_frame[CHANNELS][OS_MAX_COMMAND_LENGTH + 1];
static size_t g_frame_length[CHANNELS];
static bool g_discard[CHANNELS];
static os_equatorial_coord_t g_pending;
static bool g_pending_ra, g_pending_dec;

static bool axis_ok(uint8_t axis) { return axis < AXES; }
static bool channel_ok(uint8_t channel) { return channel < CHANNELS; }
static bool finitef_local(float value) { return isfinite((double)value) != 0; }
static bool coord_ok(os_equatorial_coord_t coord) { return finitef_local(coord.ra_hours) && finitef_local(coord.dec_degrees) && coord.ra_hours >= OS_RA_MIN_HOURS && coord.ra_hours <= OS_RA_MAX_HOURS && coord.dec_degrees >= OS_DEC_MIN_DEG && coord.dec_degrees <= OS_DEC_MAX_DEG; }
static uint32_t crc_bytes(const void *data, size_t length) { const uint8_t *p = (const uint8_t *)data; uint32_t c = 2166136261u; size_t i; for (i = 0; i < length; i++) { c ^= p[i]; c *= 16777619u; } return c; }
static int32_t clamp_i32(double value) { if (value > 2147483647.0) return INT32_MAX; if (value < -2147483648.0) return INT32_MIN; return (int32_t)llround(value); }
static double ra_scale(void) { return STEPS_RA_HOUR / (15.0 * 3600.0); }
static double dec_scale(void) { return STEPS_DEC_DEG / 3600.0; }
static void stop_axis(uint8_t axis) { if (axis_ok(axis)) { (void)os_hal_motor_set_frequency(axis, 0); (void)os_hal_motor_enable(axis, false); } }
static void stop_all(void) { stop_axis(0); stop_axis(1); g_motion.active = false; g_tracking = false; g_guide.active = false; }
static void fault_state(void) { stop_all(); g_state = OS_STATE_FAULT; }
static void set_axis(uint8_t axis, bool forward, uint32_t hz) { if (!axis_ok(axis)) return; (void)os_hal_motor_set_direction(axis, forward); (void)os_hal_motor_set_frequency(axis, hz); (void)os_hal_motor_enable(axis, hz != 0); }
static int32_t ra_steps_for(float ra_hours, float dec_degrees) { double x = (double)ra_hours * 54000.0, y = (double)dec_degrees * 3600.0, v; if (!g_cal.valid) v = x * ra_scale(); else v = g_cal.offset_ra_arcsec + g_cal.matrix_ra_to_ra * x + g_cal.matrix_dec_to_ra * y; return clamp_i32(v); }
static int32_t dec_steps_for(float ra_hours, float dec_degrees) { double x = (double)ra_hours * 54000.0, y = (double)dec_degrees * 3600.0, v; if (!g_cal.valid) v = y * dec_scale(); else v = g_cal.offset_dec_arcsec + g_cal.matrix_ra_to_dec * x + g_cal.matrix_dec_to_dec * y; return clamp_i32(v); }
static uint32_t base_tracking_hz(void) { double f = OS_SIDEREAL_RATE_ARCSEC_PER_SEC; if (g_rate == OS_TRACK_RATE_LUNAR) f *= OS_LUNAR_RATE_FACTOR; else if (g_rate == OS_TRACK_RATE_SOLAR) f *= OS_SOLAR_RATE_FACTOR; else if (g_rate == OS_TRACK_RATE_CUSTOM) f *= g_rate_factor; f *= ra_scale(); if (f < 0) return 0; if (f > MAX_HZ) return MAX_HZ; return (uint32_t)llround(f); }
static uint32_t guide_hz(void) { double f = OS_SIDEREAL_RATE_ARCSEC_PER_SEC * g_guide_rate * ra_scale(); return f < 1.0 ? 1u : (uint32_t)llround(f); }
static os_error_t persist_cfg(void);
static void tracking_apply(void) { uint32_t f = base_tracking_hz(); if (g_pec_enabled && g_pec.valid) { double phase = fmod(g_motor[0].phase, 360.0); size_t i = (size_t)phase, j = (i + 1u) % OS_PEC_TABLE_SIZE; double q = phase - (double)i, c = (1.0 - q) * g_pec.corrections[i] + q * g_pec.corrections[j], a = (double)f * (1.0 + c / 3600.0); if (a < 0) a = 0; if (a > MAX_HZ) a = MAX_HZ; f = (uint32_t)llround(a); } set_axis(0, true, f); set_axis(1, true, 0); }
static void timer_step_1ms(void) { size_t i; for (i = 0; i < AXES; i++) if (g_motor[i].enabled && g_motor[i].frequency) { double n = (double)g_motor[i].frequency / 1000.0 + g_motor[i].phase; uint32_t s = (uint32_t)floor(n); g_motor[i].phase = n - (double)s; if (s) { int64_t p = (int64_t)g_motor[i].position + (g_motor[i].forward ? (int64_t)s : -(int64_t)s); if (p > INT32_MAX) p = INT32_MAX; if (p < INT32_MIN) p = INT32_MIN; g_motor[i].position = (int32_t)p; } } }
static os_error_t start_target(int32_t axis0_target, int32_t axis1_target, os_state_t final_state) { int32_t targets[2] = {axis0_target, axis1_target}; size_t i; g_motion.active = false; g_tracking = false; g_motion.final_state = final_state; for (i = 0; i < AXES; i++) { int32_t p = os_hal_motor_get_position((uint8_t)i); g_motion.target[i] = targets[i]; if (p != targets[i]) { g_motion.active = true; g_motion.forward[i] = targets[i] > p; set_axis((uint8_t)i, g_motion.forward[i], 1); } else { stop_axis((uint8_t)i); } } g_state = OS_STATE_GOTO; return OS_ERR_NONE; }
static bool restore_cal(void) { cal_record_t r; if (os_hal_nvm_read(NVM_CAL_OFFSET, (uint8_t *)&r, sizeof r) != OS_ERR_NONE) return false; if (r.magic != CAL_MAGIC || r.crc != crc_bytes(&r, sizeof r - sizeof r.crc) || !r.calib.valid) return false; g_cal = r.calib; g_residual = r.residual; g_residual_valid = true; return true; }
static bool restore_cfg(void) { cfg_record_t r; if (os_hal_nvm_read(NVM_CFG_OFFSET, (uint8_t *)&r, sizeof r) != OS_ERR_NONE) return false; if (r.magic != CFG_MAGIC || r.crc != crc_bytes(&r, sizeof r - sizeof r.crc) || !r.site.valid) return false; g_site = r.site; g_park = r.park; g_park_custom = r.park_custom; g_rate = r.rate; g_rate_factor = r.factor; g_guide_rate = r.guide_rate; g_pec_enabled = r.pec_enabled; return true; }
static bool restore_pec(void) { pec_record_t r; if (os_hal_nvm_read(NVM_PEC_OFFSET, (uint8_t *)&r, sizeof r) != OS_ERR_NONE) return false; if (r.magic != PEC_MAGIC || r.crc != crc_bytes(&r, sizeof r - sizeof r.crc) || !r.table.valid) return false; g_pec = r.table; return true; }
static os_error_t persist_cfg(void) { cfg_record_t r; memset(&r, 0, sizeof r); r.magic = CFG_MAGIC; r.site = g_site; r.park = g_park; r.park_custom = g_park_custom; r.rate = g_rate; r.factor = g_rate_factor; r.guide_rate = g_guide_rate; r.pec_enabled = g_pec_enabled; r.crc = crc_bytes(&r, sizeof r - sizeof r.crc); return os_hal_nvm_write(NVM_CFG_OFFSET, (const uint8_t *)&r, sizeof r) == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
static os_error_t persist_cal(void) { cal_record_t r; memset(&r, 0, sizeof r); r.magic = CAL_MAGIC; r.calib = g_cal; r.residual = g_residual; r.crc = crc_bytes(&r, sizeof r - sizeof r.crc); return os_hal_nvm_write(NVM_CAL_OFFSET, (const uint8_t *)&r, sizeof r) == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
static os_error_t persist_pec(void) { pec_record_t r; memset(&r, 0, sizeof r); r.magic = PEC_MAGIC; r.table = g_pec; r.crc = crc_bytes(&r, sizeof r - sizeof r.crc); return os_hal_nvm_write(NVM_PEC_OFFSET, (const uint8_t *)&r, sizeof r) == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }

os_error_t os_hal_motor_init(uint8_t axis) { if (!axis_ok(axis)) return OS_ERR_INVALID_ARGUMENT; g_motor[axis].initialized = true; g_motor[axis].enabled = false; g_motor[axis].frequency = 0; g_motor[axis].phase = 0; return OS_ERR_NONE; }
os_error_t os_hal_motor_set_frequency(uint8_t axis, uint32_t frequency_hz) { if (!axis_ok(axis) || frequency_hz > MAX_HZ) return OS_ERR_INVALID_ARGUMENT; g_motor[axis].frequency = frequency_hz; if (!frequency_hz) g_motor[axis].enabled = false; return OS_ERR_NONE; }
os_error_t os_hal_motor_set_direction(uint8_t axis, bool forward) { if (!axis_ok(axis)) return OS_ERR_INVALID_ARGUMENT; g_motor[axis].forward = forward; return OS_ERR_NONE; }
os_error_t os_hal_motor_enable(uint8_t axis, bool enable) { if (!axis_ok(axis)) return OS_ERR_INVALID_ARGUMENT; g_motor[axis].enabled = enable; if (!enable) g_motor[axis].frequency = 0; return OS_ERR_NONE; }
int32_t os_hal_motor_get_position(uint8_t axis) { return axis_ok(axis) ? g_motor[axis].position : 0; }
os_error_t os_hal_gps_init(void) { return OS_ERR_NONE; }
os_error_t os_hal_gps_poll(os_site_info_t *site) { if (!site) return OS_ERR_INVALID_ARGUMENT; site->valid = false; return OS_ERR_GPS_NO_SIGNAL; }
os_error_t os_hal_rtc_init(void) { return OS_ERR_NONE; }
os_error_t os_hal_rtc_read(uint32_t *utc_epoch_seconds) { if (!utc_epoch_seconds) return OS_ERR_INVALID_ARGUMENT; *utc_epoch_seconds = g_utc; return g_time_valid ? OS_ERR_NONE : OS_ERR_TIMEOUT; }
os_error_t os_hal_rtc_set(uint32_t utc_epoch_seconds) { g_utc = utc_epoch_seconds; g_time_valid = true; return OS_ERR_NONE; }
os_error_t os_hal_limit_init(void) { g_limit[0] = false; g_limit[1] = false; return OS_ERR_NONE; }
bool os_hal_limit_is_triggered(uint8_t axis) { return !axis_ok(axis) || g_limit[axis]; }
os_error_t os_hal_nvm_init(void) { if (!g_nvm_ready) { memset(g_nvm, 0, sizeof g_nvm); g_nvm_ready = true; } return OS_ERR_NONE; }
os_error_t os_hal_nvm_read(uint16_t offset, uint8_t *data, uint16_t length) { if (!data || (uint32_t)offset + length > NVM_BYTES) return OS_ERR_INVALID_ARGUMENT; memcpy(data, g_nvm + offset, length); return OS_ERR_NONE; }
os_error_t os_hal_nvm_write(uint16_t offset, const uint8_t *data, uint16_t length) { if (!data || (uint32_t)offset + length > NVM_BYTES) return OS_ERR_INVALID_ARGUMENT; memcpy(g_nvm + offset, data, length); return OS_ERR_NONE; }
os_error_t os_hal_comm_init(uint8_t channel) { if (!channel_ok(channel)) return OS_ERR_INVALID_ARGUMENT; g_comm_ready[channel] = true; g_rx_head[channel] = g_rx_tail[channel] = g_tx_length[channel] = 0; return OS_ERR_NONE; }
int16_t os_hal_comm_available(uint8_t channel) { if (!channel_ok(channel) || !g_comm_ready[channel]) return 0; return (int16_t)(g_rx_tail[channel] - g_rx_head[channel]); }
char os_hal_comm_read(uint8_t channel) { if (channel_ok(channel) && os_hal_comm_available(channel) > 0) return g_rx[channel][(g_rx_head[channel]++) % sizeof g_rx[channel]]; return 0; }
os_error_t os_hal_comm_write(uint8_t channel, const char *data, size_t length) { if (!channel_ok(channel) || !data || length > OS_MAX_REPLY_LENGTH) return OS_ERR_INVALID_ARGUMENT; if (length > sizeof g_tx[channel] - g_tx_length[channel]) return OS_ERR_TIMEOUT; memcpy(g_tx[channel] + g_tx_length[channel], data, length); g_tx_length[channel] += length; return OS_ERR_NONE; }
os_error_t os_hal_buzzer_beep(uint16_t duration_ms, uint8_t count) { return duration_ms && count ? OS_ERR_NONE : OS_ERR_INVALID_ARGUMENT; }
os_error_t os_hal_timer_motor_init(void) { return OS_ERR_NONE; }

os_error_t os_init(void) { size_t i; os_error_t e; g_state = OS_STATE_INITIALIZING; g_motion = (motion_t){0}; g_guide = (os_guide_pulse_t){0}; g_guide_until = 0; g_sample_count = 0; g_residual = 0; g_residual_valid = false; g_cal = (os_calibration_t){0}; g_pec = (os_pec_table_t){0}; g_pec_enabled = false; g_site = (os_site_info_t){0,0,0,0,false}; g_park = (os_equatorial_coord_t){0,90}; g_park_custom = false; g_gps_locked = false; g_time_valid = false; g_tracking = false; g_rate = OS_TRACK_RATE_SIDEREAL; g_rate_factor = 1.0f; g_guide_rate = 0.5f; g_custom_speed = OS_SIDEREAL_RATE_ARCSEC_PER_SEC; g_pending_ra = false; g_pending_dec = false; g_tick_ms = 0; for (i = 0; i < CHANNELS; i++) { g_comm_ready[i] = false; g_frame_length[i] = 0; g_discard[i] = false; } e = os_hal_nvm_init(); if (e != OS_ERR_NONE) { fault_state(); return e; } if (!restore_cfg()) { g_site = (os_site_info_t){0,0,0,0,true}; g_park = (os_equatorial_coord_t){0,90}; } else { (void)restore_pec(); } (void)restore_cal(); for (i = 0; i < CHANNELS; i++) if ((e = os_hal_comm_init((uint8_t)i)) != OS_ERR_NONE) { fault_state(); return e; } for (i = 0; i < AXES; i++) { if ((e = os_hal_motor_init((uint8_t)i)) != OS_ERR_NONE) { fault_state(); return e; } set_axis((uint8_t)i, true, 0); } if (os_hal_gps_init() != OS_ERR_NONE) { fault_state(); return OS_ERR_GPS_NO_SIGNAL; } (void)os_hal_rtc_init(); (void)os_hal_limit_init(); if ((e = os_hal_timer_motor_init()) != OS_ERR_NONE) { fault_state(); return e; } { os_site_info_t s; uint32_t t; if (os_hal_gps_poll(&s) == OS_ERR_NONE && s.valid && s.latitude_degrees >= -90 && s.latitude_degrees <= 90 && s.longitude_degrees >= -180 && s.longitude_degrees <= 180) { g_site = s; g_gps_locked = true; g_time_valid = true; g_utc = s.utc_epoch_seconds; (void)os_hal_rtc_set(g_utc); } else if (os_hal_rtc_read(&t) == OS_ERR_NONE) { g_utc = t; g_time_valid = true; g_site.valid = true; g_site.utc_epoch_seconds = t; } } g_state = OS_STATE_IDLE_TRACKING; if (g_time_valid && g_site.valid) { g_tracking = true; tracking_apply(); } return OS_ERR_NONE; }

void os_loop_iteration(void) { size_t c, i; char ch; g_tick_ms++; timer_step_1ms(); if (g_state == OS_STATE_FAULT) return; for (c = 0; c < CHANNELS; c++) while (os_hal_comm_available((uint8_t)c) > 0) { ch = os_hal_comm_read((uint8_t)c); if (g_discard[c]) { if (ch == '#') { g_discard[c] = false; g_frame_length[c] = 0; } continue; } if (ch == ':') { g_frame_length[c] = 1; g_frame[c][0] = ch; continue; } if (!g_frame_length[c]) continue; if (g_frame_length[c] >= OS_MAX_COMMAND_LENGTH) { g_discard[c] = true; continue; } g_frame[c][g_frame_length[c]++] = ch; if (ch == '#') { char r[OS_MAX_REPLY_LENGTH]; size_t n = 0; (void)os_command_parse(g_frame[c], g_frame_length[c], (uint8_t)c, r, sizeof r, &n); g_frame_length[c] = 0; } } for (i = 0; i < AXES; i++) if (os_hal_limit_is_triggered((uint8_t)i)) { stop_axis((uint8_t)i); if (g_motion.active || g_tracking) fault_state(); } if (g_guide.active && g_tick_ms >= g_guide_until) { g_guide.active = false; g_guide.duration_ms = 0; } if (g_motion.active) { bool done = true; for (i = 0; i < AXES; i++) { int32_t p = os_hal_motor_get_position((uint8_t)i), t = g_motion.target[i]; int64_t d = (int64_t)t - p; uint32_t hz; double ad = fabs((double)d); if (d) { done = false; hz = (uint32_t)(100.0 + ad * 20.0); if (hz > 3000) hz = 3000; if (ad < 5) hz = 1; set_axis((uint8_t)i, g_motion.forward[i], hz); } else { stop_axis((uint8_t)i); } } if (done) { os_state_t final = g_motion.final_state; g_motion.active = false; stop_axis(0); stop_axis(1); if (final == OS_STATE_PARKED) { g_state = OS_STATE_PARKED; g_tracking = false; (void)persist_cfg(); } else { g_state = OS_STATE_IDLE_TRACKING; g_tracking = g_time_valid && g_site.valid; if (g_tracking) tracking_apply(); (void)os_hal_buzzer_beep(100, 1); } } } else if (g_tracking && g_state == OS_STATE_IDLE_TRACKING) { tracking_apply(); if (g_guide.active) { uint32_t f = base_tracking_hz(), gf = guide_hz(); if (g_guide.dec_priority && (g_guide.direction_north || (!g_guide.direction_east && !g_guide.direction_north))) set_axis(1, g_guide.direction_north, gf); else set_axis(0, g_guide.direction_east, f + gf); } } }

static os_error_t reply_copy(char *buffer, size_t buffer_size, size_t *reply_length, const char *text) { size_t n; if (!buffer || !reply_length || !text) return OS_ERR_INVALID_ARGUMENT; n = strlen(text); if (n >= buffer_size || n > OS_MAX_REPLY_LENGTH) return OS_ERR_INVALID_ARGUMENT; memcpy(buffer, text, n + 1); *reply_length = n; return OS_ERR_NONE; }
static bool parse_hms(const char *p, float *value) { int h, m; float s; if (sscanf(p, "%d:%d:%f#", &h, &m, &s) != 3 || h < 0 || m < 0 || m >= 60 || s < 0 || s >= 60 || !finitef_local(s)) return false; *value = (float)h + m / 60.0f + s / 3600.0f; return h <= 24 && *value <= 24; }
static bool parse_dms(const char *p, float *value) { char sign = '+'; int d, m; float s; if (*p == '+' || *p == '-') sign = *p++; if (sscanf(p, "%d*%d:%f#", &d, &m, &s) != 3 || d > 90 || m < 0 || m >= 60 || s < 0 || s >= 60) return false; *value = (sign == '-' ? -1.0f : 1.0f) * ((float)d + m / 60.0f + s / 3600.0f); return *value >= -90 && *value <= 90; }
os_error_t os_command_parse(const char *command, size_t length, uint8_t source_channel, char *reply_buffer, size_t reply_buffer_size, size_t *reply_length) { char r[OS_MAX_REPLY_LENGTH] = {0}; os_error_t e = OS_ERR_NONE; os_equatorial_coord_t q; float x; if (!command || !reply_buffer || !reply_length || !channel_ok(source_channel) || length < 3 || length > OS_MAX_COMMAND_LENGTH || reply_buffer_size == 0) return OS_ERR_INVALID_ARGUMENT; if (command[0] != ':' || command[length - 1] != '#') e = OS_ERR_COMMAND_FORMAT; else if (length == 4 && !memcmp(command, ":GR#", 4)) { e = os_query_coordinates(&q); if (!e) snprintf(r, sizeof r, "%02d:%02d:%02d#", (int)q.ra_hours, (int)(q.ra_hours * 60) % 60, (int)(q.ra_hours * 3600) % 60); } else if (length == 4 && !memcmp(command, ":GD#", 4)) { e = os_query_coordinates(&q); if (!e) snprintf(r, sizeof r, "%+03d*%02d:%02d#", (int)q.dec_degrees, abs((int)(q.dec_degrees * 60) % 60), abs((int)(q.dec_degrees * 3600) % 60)); } else if (length == 5 && !memcmp(command, ":GVP#", 5)) snprintf(r, sizeof r, "OnStep %d.%d.%d#", OS_FIRMWARE_VERSION_MAJOR, OS_FIRMWARE_VERSION_MINOR, OS_FIRMWARE_VERSION_PATCH); else if (length >= 5 && !memcmp(command, ":Sr", 3)) { if (!parse_hms(command + 3, &x)) e = OS_ERR_INVALID_ARGUMENT; else { g_pending.ra_hours = x; g_pending_ra = true; strcpy(r, "1#"); } } else if (length >= 5 && !memcmp(command, ":Sd", 3)) { if (!parse_dms(command + 3, &x)) e = OS_ERR_INVALID_ARGUMENT; else { g_pending.dec_degrees = x; g_pending_dec = true; strcpy(r, "1#"); } } else if (length == 4 && !memcmp(command, ":MS#", 4)) { if (!g_pending_ra || !g_pending_dec) e = OS_ERR_INVALID_STATE; else e = os_goto_equatorial(g_pending); } else if (length == 3 && !memcmp(command, ":Q#", 3)) e = os_goto_abort(); else if (length == 4 && !memcmp(command, ":hP#", 4)) e = os_park(); else if (length == 4 && !memcmp(command, ":hO#", 4)) e = os_unpark(); else if (length == 4 && command[1] == 'M' && command[2] >= 'e' && command[2] <= 's') { os_direction_t d = command[2] == 'e' ? OS_DIRECTION_EAST : command[2] == 'w' ? OS_DIRECTION_WEST : command[2] == 'n' ? OS_DIRECTION_NORTH : OS_DIRECTION_SOUTH; e = os_move_start(d, OS_SPEED_FAST); } else if (length == 4 && !memcmp(command, ":Qe#", 4)) e = os_move_stop(); else if (length == 5 && !memcmp(command, ":GT#", 4)) snprintf(r, sizeof r, "%lu#", (unsigned long)g_utc); else e = OS_ERR_COMMAND_FORMAT; if (e) snprintf(r, sizeof r, "E%d#", (int)e); else if (!r[0]) strcpy(r, "1#"); if (reply_copy(reply_buffer, reply_buffer_size, reply_length, r) != OS_ERR_NONE) return OS_ERR_INVALID_ARGUMENT; (void)os_hal_comm_write(source_channel, reply_buffer, *reply_length); return e; }

os_error_t os_goto_equatorial(os_equatorial_coord_t target) { if (!coord_ok(target)) return OS_ERR_INVALID_ARGUMENT; if (g_state == OS_STATE_FAULT || g_state == OS_STATE_PARKED || g_state == OS_STATE_ALIGNMENT || !g_time_valid || !g_site.valid) return OS_ERR_INVALID_STATE; if (os_hal_limit_is_triggered(0) || os_hal_limit_is_triggered(1)) return OS_ERR_LIMIT_TRIGGERED; return start_target(ra_steps_for(target.ra_hours, target.dec_degrees), dec_steps_for(target.ra_hours, target.dec_degrees), OS_STATE_GOTO); }
os_error_t os_goto_horizontal(os_horizontal_coord_t target) { double lat, alt, az, lst, h, dec, ra; if (!finitef_local(target.azimuth_degrees) || !finitef_local(target.altitude_degrees) || target.azimuth_degrees < 0 || target.azimuth_degrees > 360 || target.altitude_degrees < -90 || target.altitude_degrees > 90) return OS_ERR_INVALID_ARGUMENT; if (!g_time_valid || !g_site.valid) return OS_ERR_INVALID_STATE; lat = g_site.latitude_degrees * PI / 180; alt = target.altitude_degrees * PI / 180; az = target.azimuth_degrees * PI / 180; dec = asin(sin(alt) * sin(lat) + cos(alt) * cos(lat) * cos(az)); h = atan2(-sin(az) * cos(alt), sin(alt) * cos(lat) - cos(alt) * sin(lat) * cos(az)); lst = fmod((double)g_utc / 86164.0905 * 24 + g_site.longitude_degrees / 15, 24); if (lst < 0) lst += 24; ra = lst - h * 12 / PI; while (ra < 0) ra += 24; while (ra >= 24) ra -= 24; return os_goto_equatorial((os_equatorial_coord_t){(float)ra, (float)(dec * 180 / PI)}); }
os_error_t os_goto_abort(void) { if (g_state != OS_STATE_GOTO) return OS_ERR_INVALID_STATE; stop_all(); g_state = OS_STATE_IDLE_TRACKING; if (g_time_valid && g_site.valid) { g_tracking = true; tracking_apply(); } return OS_ERR_NONE; }
os_error_t os_tracking_set_rate(os_track_rate_t rate, float custom_factor) { if (rate < OS_TRACK_RATE_SIDEREAL || rate > OS_TRACK_RATE_CUSTOM || !finitef_local(custom_factor) || (rate == OS_TRACK_RATE_CUSTOM && custom_factor <= 0)) return OS_ERR_INVALID_ARGUMENT; g_rate = rate; g_rate_factor = custom_factor; (void)persist_cfg(); if (g_tracking) tracking_apply(); return OS_ERR_NONE; }
os_error_t os_tracking_get_rate(os_track_rate_t *rate, float *custom_factor) { if (!rate || !custom_factor) return OS_ERR_INVALID_ARGUMENT; *rate = g_rate; *custom_factor = g_rate_factor; return OS_ERR_NONE; }
os_error_t os_tracking_enable(void) { if (g_state == OS_STATE_FAULT || g_state == OS_STATE_PARKED || !g_time_valid || !g_site.valid) return OS_ERR_INVALID_STATE; g_tracking = true; g_state = OS_STATE_IDLE_TRACKING; tracking_apply(); return OS_ERR_NONE; }
os_error_t os_tracking_disable(void) { g_tracking = false; stop_axis(0); stop_axis(1); if (g_state == OS_STATE_IDLE_TRACKING) g_state = OS_STATE_INITIALIZING; return OS_ERR_NONE; }
os_error_t os_guide_pulse(os_direction_t direction, uint32_t duration_ms) { if (direction < OS_DIRECTION_NORTH || direction > OS_DIRECTION_WEST || duration_ms == 0) return OS_ERR_INVALID_ARGUMENT; if (g_state != OS_STATE_IDLE_TRACKING) return OS_ERR_INVALID_STATE; g_guide = (os_guide_pulse_t){true, duration_ms, g_guide_rate, direction == OS_DIRECTION_EAST, direction == OS_DIRECTION_NORTH, true}; g_guide_until = g_tick_ms + duration_ms; return OS_ERR_NONE; }
os_error_t os_guide_set_rate(float rate_fraction) { if (!finitef_local(rate_fraction) || rate_fraction < OS_GUIDE_RATE_MIN || rate_fraction > OS_GUIDE_RATE_MAX) return OS_ERR_INVALID_ARGUMENT; g_guide_rate = rate_fraction; (void)persist_cfg(); return OS_ERR_NONE; }
os_error_t os_guide_get_state(os_guide_pulse_t *pulse) { if (!pulse) return OS_ERR_INVALID_ARGUMENT; *pulse = g_guide; return OS_ERR_NONE; }
os_error_t os_align_begin(os_align_mode_t mode) { if (mode < OS_ALIGN_1STAR || mode > OS_ALIGN_NSTAR) return OS_ERR_INVALID_ARGUMENT; if (g_state == OS_STATE_FAULT || g_state == OS_STATE_GOTO || g_state == OS_STATE_PARKED) return OS_ERR_INVALID_STATE; stop_all(); g_align_mode = mode; g_sample_count = 0; g_residual_valid = false; g_state = OS_STATE_ALIGNMENT; return OS_ERR_NONE; }
os_error_t os_align_accept_star(os_equatorial_coord_t star_coord, os_motor_position_t motor_pos) { if (!coord_ok(star_coord)) return OS_ERR_INVALID_ARGUMENT; if (g_state != OS_STATE_ALIGNMENT || g_sample_count >= OS_CALIBRATION_MAX_STARS) return OS_ERR_INVALID_STATE; g_samples[g_sample_count++] = (sample_t){star_coord, motor_pos}; return OS_ERR_NONE; }
static bool solve3(double a[3][3], double b[3], double x[3]) { int i, j, k, p; double q, t; for (i = 0; i < 3; i++) { p = i; for (j = i + 1; j < 3; j++) if (fabs(a[j][i]) > fabs(a[p][i])) p = j; if (fabs(a[p][i]) < 1e-12) return false; if (p != i) { for (k = 0; k < 3; k++) { t = a[i][k]; a[i][k] = a[p][k]; a[p][k] = t; } t = b[i]; b[i] = b[p]; b[p] = t; } for (j = i + 1; j < 3; j++) { q = a[j][i] / a[i][i]; for (k = i; k < 3; k++) a[j][k] -= q * a[i][k]; b[j] -= q * b[i]; } } for (i = 2; i >= 0; i--) { t = b[i]; for (j = i + 1; j < 3; j++) t -= a[i][j] * x[j]; x[i] = t / a[i][i]; } return true; }
static bool fit_axis(size_t n, bool dec, double out[3]) { double a[3][3] = {{0}}, b[3] = {0}; size_t i; for (i = 0; i < n; i++) { double y = g_samples[i].star.ra_hours * 54000, z = g_samples[i].star.dec_degrees * 3600, v = dec ? g_samples[i].motor.dec_steps : g_samples[i].motor.ra_steps; a[0][0] += 1; a[0][1] += y; a[0][2] += z; a[1][1] += y * y; a[1][2] += y * z; a[2][2] += z * z; b[0] += v; b[1] += y * v; b[2] += z * v; } a[1][0] = a[0][1]; a[2][0] = a[0][2]; a[2][1] = a[1][2]; return solve3(a, b, out); }
os_error_t os_align_compute(void) { size_t need, i; double ra[3], de[3], det, maxerr = 0; os_calibration_t c; if (g_align_mode == OS_ALIGN_1STAR) need = 1; else if (g_align_mode == OS_ALIGN_2STAR) need = 2; else need = 3; if (g_sample_count < need) return OS_ERR_INVALID_STATE; memset(&c, 0, sizeof c); if (g_align_mode == OS_ALIGN_1STAR) { c.matrix_ra_to_ra = (float)ra_scale(); c.matrix_dec_to_dec = (float)dec_scale(); c.offset_ra_arcsec = (float)(g_samples[0].motor.ra_steps - ra_scale() * g_samples[0].star.ra_hours * 54000); c.offset_dec_arcsec = (float)(g_samples[0].motor.dec_steps - dec_scale() * g_samples[0].star.dec_degrees * 3600); } else if (g_align_mode == OS_ALIGN_2STAR) { double dx = (g_samples[1].star.ra_hours - g_samples[0].star.ra_hours) * 54000, dy = (g_samples[1].star.dec_degrees - g_samples[0].star.dec_degrees) * 3600; if (fabs(dx) < 1e-9 || fabs(dy) < 1e-9) return OS_ERR_CALIBRATION_FAILED; c.matrix_ra_to_ra = (float)((g_samples[1].motor.ra_steps - g_samples[0].motor.ra_steps) / dx); c.matrix_dec_to_dec = (float)((g_samples[1].motor.dec_steps - g_samples[0].motor.dec_steps) / dy); c.offset_ra_arcsec = (float)(g_samples[0].motor.ra_steps - c.matrix_ra_to_ra * g_samples[0].star.ra_hours * 54000); c.offset_dec_arcsec = (float)(g_samples[0].motor.dec_steps - c.matrix_dec_to_dec * g_samples[0].star.dec_degrees * 3600); } else { double x1 = g_samples[0].star.ra_hours * 54000, y1 = g_samples[0].star.dec_degrees * 3600, x2 = g_samples[1].star.ra_hours * 54000, y2 = g_samples[1].star.dec_degrees * 3600, x3 = g_samples[2].star.ra_hours * 54000, y3 = g_samples[2].star.dec_degrees * 3600; det = x1 * (y2 - y3) - x2 * (y1 - y3) + x3 * (y1 - y2); if (fabs(det) < 1e-9 || !fit_axis(g_sample_count, false, ra) || !fit_axis(g_sample_count, true, de)) return OS_ERR_CALIBRATION_FAILED; c.offset_ra_arcsec = (float)ra[0]; c.matrix_ra_to_ra = (float)ra[1]; c.matrix_dec_to_ra = (float)ra[2]; c.offset_dec_arcsec = (float)de[0]; c.matrix_ra_to_dec = (float)de[1]; c.matrix_dec_to_dec = (float)de[2]; } c.valid = true; for (i = 0; i < g_sample_count; i++) { double x = g_samples[i].star.ra_hours * 54000, y = g_samples[i].star.dec_degrees * 3600, a = c.offset_ra_arcsec + c.matrix_ra_to_ra * x + c.matrix_dec_to_ra * y, b = c.offset_dec_arcsec + c.matrix_ra_to_dec * x + c.matrix_dec_to_dec * y, e = hypot((a - g_samples[i].motor.ra_steps) / ra_scale(), (b - g_samples[i].motor.dec_steps) / dec_scale()); if (e > maxerr) maxerr = e; } if (g_sample_count >= 4 && maxerr > 360) return OS_ERR_CALIBRATION_FAILED; g_cal = c; g_residual = (float)maxerr; g_residual_valid = true; if (persist_cal() != OS_ERR_NONE) return OS_ERR_NVM_FAULT; g_state = OS_STATE_IDLE_TRACKING; return os_tracking_enable(); }
os_error_t os_align_get_residual(float *residual_arcsec) { if (!residual_arcsec) return OS_ERR_INVALID_ARGUMENT; if (!g_residual_valid) return OS_ERR_INVALID_STATE; *residual_arcsec = g_residual; return OS_ERR_NONE; }
os_error_t os_align_abort(void) { if (g_state != OS_STATE_ALIGNMENT) return OS_ERR_INVALID_STATE; g_sample_count = 0; g_state = OS_STATE_IDLE_TRACKING; return os_tracking_enable(); }
os_error_t os_park_set_position(os_equatorial_coord_t park_pos) { if (!coord_ok(park_pos)) return OS_ERR_INVALID_ARGUMENT; g_park = park_pos; g_park_custom = true; return persist_cfg(); }
os_error_t os_park(void) { os_equatorial_coord_t p; if (g_state == OS_STATE_FAULT || g_state == OS_STATE_PARKED) return OS_ERR_INVALID_STATE; if (os_hal_limit_is_triggered(0) || os_hal_limit_is_triggered(1)) return OS_ERR_LIMIT_TRIGGERED; p = g_park_custom ? g_park : (os_equatorial_coord_t){0, 90}; return start_target(ra_steps_for(p.ra_hours, p.dec_degrees), dec_steps_for(p.ra_hours, p.dec_degrees), OS_STATE_PARKED); }
os_error_t os_unpark(void) { size_t i; if (g_state != OS_STATE_PARKED) return OS_ERR_INVALID_STATE; for (i = 0; i < CHANNELS; i++) if (os_hal_comm_init((uint8_t)i) != OS_ERR_NONE) { fault_state(); return OS_ERR_NOT_SUPPORTED; } for (i = 0; i < AXES; i++) { if (os_hal_motor_init((uint8_t)i) != OS_ERR_NONE) { fault_state(); return OS_ERR_MOTOR_DRIVER_FAULT; } set_axis((uint8_t)i, true, 0); } if (os_hal_rtc_read(&g_utc) != OS_ERR_NONE) { fault_state(); return OS_ERR_TIMEOUT; } g_time_valid = true; g_state = OS_STATE_IDLE_TRACKING; return os_tracking_enable(); }
os_error_t os_move_start(os_direction_t direction, os_speed_level_t speed) { uint8_t axis; bool forward; uint32_t hz; if (direction < OS_DIRECTION_NORTH || direction > OS_DIRECTION_WEST || speed < OS_SPEED_SLOW || speed > OS_SPEED_CUSTOM) return OS_ERR_INVALID_ARGUMENT; if (g_state == OS_STATE_FAULT || g_state == OS_STATE_PARKED) return OS_ERR_INVALID_STATE; axis = (direction == OS_DIRECTION_EAST || direction == OS_DIRECTION_WEST) ? 0 : 1; forward = (direction == OS_DIRECTION_EAST || direction == OS_DIRECTION_NORTH); if (os_hal_limit_is_triggered(axis)) return OS_ERR_LIMIT_TRIGGERED; hz = speed == OS_SPEED_SLOW ? 10 : speed == OS_SPEED_MEDIUM ? 100 : speed == OS_SPEED_FAST ? 1000 : (uint32_t)fmax(1, g_custom_speed * STEPS_DEC_DEG / 3600); stop_all(); set_axis(axis, forward, hz); g_state = OS_STATE_MANUAL_MOTION; return OS_ERR_NONE; }
os_error_t os_move_stop(void) { if (g_state != OS_STATE_MANUAL_MOTION) return OS_ERR_INVALID_STATE; stop_all(); g_state = OS_STATE_IDLE_TRACKING; return os_tracking_enable(); }
os_error_t os_move_set_custom_speed(float arcsec_per_sec) { if (!finitef_local(arcsec_per_sec) || arcsec_per_sec <= 0) return OS_ERR_INVALID_ARGUMENT; g_custom_speed = arcsec_per_sec; return OS_ERR_NONE; }
os_error_t os_query_state(os_state_t *state) { if (!state) return OS_ERR_INVALID_ARGUMENT; *state = g_state; return OS_ERR_NONE; }
os_error_t os_query_coordinates(os_equatorial_coord_t *coord) { double a, b, d; int32_t p, q; if (!coord) return OS_ERR_INVALID_ARGUMENT; p = os_hal_motor_get_position(0); q = os_hal_motor_get_position(1); if (!g_cal.valid) { coord->ra_hours = (float)p / STEPS_RA_HOUR; coord->dec_degrees = (float)q / STEPS_DEC_DEG; } else { d = (double)g_cal.matrix_ra_to_ra * g_cal.matrix_dec_to_dec - (double)g_cal.matrix_dec_to_ra * g_cal.matrix_ra_to_dec; if (fabs(d) < 1e-12) return OS_ERR_CALIBRATION_FAILED; a = ((p - g_cal.offset_ra_arcsec) * g_cal.matrix_dec_to_dec - (q - g_cal.offset_dec_arcsec) * g_cal.matrix_dec_to_ra) / d; b = ((double)g_cal.matrix_ra_to_ra * (q - g_cal.offset_dec_arcsec) - (double)g_cal.matrix_ra_to_dec * (p - g_cal.offset_ra_arcsec)) / d; coord->ra_hours = (float)(a / 54000); coord->dec_degrees = (float)(b / 3600); } while (coord->ra_hours < 0) coord->ra_hours += 24; while (coord->ra_hours >= 24) coord->ra_hours -= 24; return OS_ERR_NONE; }
os_error_t os_query_site(os_site_info_t *site) { if (!site) return OS_ERR_INVALID_ARGUMENT; *site = g_site; return OS_ERR_NONE; }
os_error_t os_query_motor_position(os_motor_position_t *pos) { if (!pos) return OS_ERR_INVALID_ARGUMENT; pos->ra_steps = os_hal_motor_get_position(0); pos->dec_steps = os_hal_motor_get_position(1); return OS_ERR_NONE; }
os_error_t os_query_firmware_version(uint8_t *major, uint8_t *minor, uint8_t *patch) { if (!major || !minor || !patch) return OS_ERR_INVALID_ARGUMENT; *major = OS_FIRMWARE_VERSION_MAJOR; *minor = OS_FIRMWARE_VERSION_MINOR; *patch = OS_FIRMWARE_VERSION_PATCH; return OS_ERR_NONE; }
os_error_t os_query_is_moving(bool *moving) { if (!moving) return OS_ERR_INVALID_ARGUMENT; *moving = g_motion.active || g_state == OS_STATE_MANUAL_MOTION; return OS_ERR_NONE; }
os_error_t os_query_gps_locked(bool *locked) { if (!locked) return OS_ERR_INVALID_ARGUMENT; *locked = g_gps_locked; return OS_ERR_NONE; }
os_error_t os_pec_enable(bool enable) { g_pec_enabled = enable; return persist_cfg(); }
os_error_t os_pec_load_table(const os_pec_table_t *table) { if (!table || !table->valid) return OS_ERR_INVALID_ARGUMENT; g_pec = *table; return persist_pec(); }
os_error_t os_pec_get_table(os_pec_table_t *table) { if (!table) return OS_ERR_INVALID_ARGUMENT; *table = g_pec; return OS_ERR_NONE; }
os_error_t os_pec_record_phase(float worm_phase_deg, int16_t error_arcsec) { size_t i; if (!finitef_local(worm_phase_deg) || worm_phase_deg < 0 || worm_phase_deg > 360) return OS_ERR_INVALID_ARGUMENT; i = worm_phase_deg >= 360 ? 0 : (size_t)floor(worm_phase_deg); g_pec.corrections[i] = error_arcsec; g_pec.valid = true; return persist_pec(); }
os_error_t os_calibration_get(os_calibration_t *calib) { if (!calib) return OS_ERR_INVALID_ARGUMENT; *calib = g_cal; return OS_ERR_NONE; }
os_error_t os_calibration_clear(void) { os_calibration_t z = {0}; if (os_hal_nvm_write(NVM_CAL_OFFSET, (const uint8_t *)&z, sizeof z) != OS_ERR_NONE) return OS_ERR_NVM_FAULT; g_cal = z; g_residual = 0; g_residual_valid = false; return OS_ERR_NONE; }