#include "6_generated_code.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>

#define AXES 2u
#define CHANNELS 4u
#define LOOP_MS 50u
#define MANUAL_TIMEOUT_MS 10000u
#define NVM_TOTAL 1024u
#define CAL_OFF 0u
#define CFG_OFF 256u
#define PEC_OFF 512u
#define MAGIC_CAL 0x4f534341u
#define MAGIC_CFG 0x4f534346u
#ifndef OS_MOUNT_TYPE
#define OS_MOUNT_TYPE OS_MOUNT_EQUATORIAL
#endif
#ifndef OS_STEPS_PER_ARCSEC
#define OS_STEPS_PER_ARCSEC 1.0
#endif
#ifndef OS_MAX_MOTOR_FREQUENCY_HZ
#define OS_MAX_MOTOR_FREQUENCY_HZ ((uint32_t)(OS_GOTO_SPEED_MAX_DEG_PER_SEC * 3600.0 * OS_STEPS_PER_ARCSEC + 0.5))
#endif
#ifndef OS_MANUAL_SPEED_SLOW_ARCSEC
#define OS_MANUAL_SPEED_SLOW_ARCSEC 30.0f
#endif
#ifndef OS_MANUAL_SPEED_MEDIUM_ARCSEC
#define OS_MANUAL_SPEED_MEDIUM_ARCSEC 300.0f
#endif
#ifndef OS_MANUAL_SPEED_FAST_ARCSEC
#define OS_MANUAL_SPEED_FAST_ARCSEC 1200.0f
#endif
#define OS_PI 3.1415926535897932384626433832795

typedef struct { uint32_t magic; uint32_t crc; os_calibration_t value; } cal_record_t;
typedef struct { uint32_t magic; uint32_t crc; os_equatorial_coord_t park; os_site_info_t site; os_track_rate_t rate; float custom_factor; float guide_rate; float move_speed; os_motor_position_t position; } cfg_record_t;
typedef struct { os_equatorial_coord_t c; os_motor_position_t p; } star_t;
typedef struct { bool active; bool parking; os_motor_position_t target; uint32_t frequency[AXES]; } motion_t;
typedef struct { bool active; bool forward; uint8_t axis; uint32_t frequency; } manual_t;

static os_state_t state;
static os_site_info_t site;
static bool gps_locked, time_valid, tracking_enabled, nvm_fault;
static os_track_rate_t track_rate;
static float custom_factor, guide_rate, custom_move_speed;
static os_guide_pulse_t guide;
static os_direction_t guide_direction;
static uint32_t guide_left, manual_left, elapsed_ms;
static os_calibration_t calibration;
static float residual;
static bool residual_valid;
static os_align_mode_t align_mode;
static uint8_t align_count;
static star_t stars[OS_CALIBRATION_MAX_STARS];
static os_pec_table_t pec;
static bool pec_enabled;
static os_equatorial_coord_t current_coord, target_coord, park_coord;
static bool custom_park;
static motion_t motion;
static manual_t manual;
static char command_buffer[CHANNELS][OS_MAX_COMMAND_LENGTH];
static size_t command_length[CHANNELS];
static float set_ra, set_dec;

static bool h_motor_initialized[AXES], h_motor_enabled[AXES], h_motor_direction[AXES];
static uint32_t h_motor_frequency[AXES];
static int32_t h_motor_position[AXES];
static double h_motor_remainder[AXES];
static bool h_limit[AXES], h_nvm_ready, h_rtc_ready, h_gps_ready;
static uint32_t h_rtc_epoch;
static os_site_info_t h_gps_site;
static uint8_t h_nvm[NVM_TOTAL];
static char h_rx[CHANNELS][OS_MAX_COMMAND_LENGTH * 4u];
static size_t h_rx_head[CHANNELS], h_rx_tail[CHANNELS];
static char h_tx[CHANNELS][OS_MAX_REPLY_LENGTH * 8u];
static size_t h_tx_length[CHANNELS];
static struct { uint16_t duration; uint8_t count; } h_buzzer[8];
static uint8_t h_buzzer_head, h_buzzer_tail;

static bool valid_axis(uint8_t a) { return a < AXES; }
static bool valid_channel(uint8_t c) { return c < CHANNELS; }
static bool valid_direction(os_direction_t d) { return d >= OS_DIRECTION_NORTH && d <= OS_DIRECTION_WEST; }
static bool finitef(float x) { return isfinite((double)x) != 0; }
static bool valid_eq(os_equatorial_coord_t c) { return finitef(c.ra_hours) && finitef(c.dec_degrees) && c.ra_hours >= OS_RA_MIN_HOURS && c.ra_hours <= OS_RA_MAX_HOURS && c.dec_degrees >= OS_DEC_MIN_DEG && c.dec_degrees <= OS_DEC_MAX_DEG; }
static double ra_arcsec(os_equatorial_coord_t c) { return (double)c.ra_hours * 54000.0; }
static double dec_arcsec(os_equatorial_coord_t c) { return (double)c.dec_degrees * 3600.0; }
static int32_t clamp_i32(double x) { if (x >= INT32_MAX) return INT32_MAX; if (x <= INT32_MIN) return INT32_MIN; return (int32_t)llround(x); }
static uint32_t frequency_for(double arcsec_per_sec) { double f = fabs(arcsec_per_sec) * OS_STEPS_PER_ARCSEC; if (f < 0.5) return 0; if (f > OS_MAX_MOTOR_FREQUENCY_HZ) f = OS_MAX_MOTOR_FREQUENCY_HZ; return (uint32_t)llround(f); }
static uint32_t rate_frequency(double factor) { return frequency_for(OS_SIDEREAL_RATE_ARCSEC_PER_SEC * factor); }
static uint32_t crc32(const uint8_t *p, size_t n) { uint32_t c = 0xffffffffu; size_t i; int b; for (i = 0; i < n; ++i) { c ^= p[i]; for (b = 0; b < 8; ++b) c = (c >> 1) ^ ((uint32_t)-(int)(c & 1u) & 0xedb88320u); } return ~c; }
static void reply_text(char *b, size_t z, size_t *n, const char *s) { size_t k; if (!n) return; *n = 0; if (!b || z == 0 || !s) return; k = strlen(s); if (k >= z) k = z - 1; memcpy(b, s, k); b[k] = 0; *n = k; }
static void reply_error(char *b, size_t z, size_t *n, os_error_t e) { char s[32]; snprintf(s, sizeof s, "E%d#", (int)e); reply_text(b, z, n, s); }
static os_motor_position_t raw_position(void) { os_motor_position_t p; p.ra_steps = os_hal_motor_get_position(0); p.dec_steps = os_hal_motor_get_position(1); return p; }
static os_motor_position_t to_steps(os_equatorial_coord_t c, const os_calibration_t *cal) { double x = ra_arcsec(c), y = dec_arcsec(c), a = x, d = y; os_motor_position_t p; if (cal && cal->valid) { a = x * cal->matrix_ra_to_ra + y * cal->matrix_dec_to_ra + cal->offset_ra_arcsec; d = x * cal->matrix_ra_to_dec + y * cal->matrix_dec_to_dec + cal->offset_dec_arcsec; } p.ra_steps = clamp_i32(a * OS_STEPS_PER_ARCSEC); p.dec_steps = clamp_i32(d * OS_STEPS_PER_ARCSEC); return p; }
static os_equatorial_coord_t from_steps(os_motor_position_t p) { double x = p.ra_steps / OS_STEPS_PER_ARCSEC, y = p.dec_steps / OS_STEPS_PER_ARCSEC; os_equatorial_coord_t c; if (calibration.valid) { double det = calibration.matrix_ra_to_ra * calibration.matrix_dec_to_dec - calibration.matrix_dec_to_ra * calibration.matrix_ra_to_dec; if (fabs(det) > 1e-14) { double xx = x - calibration.offset_ra_arcsec, yy = y - calibration.offset_dec_arcsec; x = (calibration.matrix_dec_to_dec * xx - calibration.matrix_dec_to_ra * yy) / det; y = (calibration.matrix_ra_to_ra * yy - calibration.matrix_ra_to_dec * xx) / det; } } c.ra_hours = (float)(x / 54000.0); while (c.ra_hours < 0) c.ra_hours += 24.0f; while (c.ra_hours > 24.0f) c.ra_hours -= 24.0f; c.dec_degrees = (float)(y / 3600.0); if (c.dec_degrees < -90) c.dec_degrees = -90; if (c.dec_degrees > 90) c.dec_degrees = 90; return c; }
static void stop_axis(uint8_t a) { if (valid_axis(a)) { (void)os_hal_motor_set_frequency(a, 0); (void)os_hal_motor_enable(a, false); } }
static void stop_motion(void) { stop_axis(0); stop_axis(1); memset(&motion, 0, sizeof motion); memset(&manual, 0, sizeof manual); memset(&guide, 0, sizeof guide); guide_left = 0; }
static bool blocked(uint8_t a, bool forward) { (void)forward; return os_hal_limit_is_triggered(a); }
static os_error_t motor_command(uint8_t a, int32_t direction, uint32_t f) { os_error_t e; if (!valid_axis(a)) return OS_ERR_INVALID_ARGUMENT; if (!direction || !f) { stop_axis(a); return OS_ERR_NONE; } if (blocked(a, direction > 0)) { stop_axis(a); return OS_ERR_LIMIT_TRIGGERED; } e = os_hal_motor_set_direction(a, direction > 0); if (e != OS_ERR_NONE) return e; e = os_hal_motor_enable(a, true); if (e != OS_ERR_NONE) return e; return os_hal_motor_set_frequency(a, f); }
static double julian_day(uint32_t t) { return 2440587.5 + (double)t / 86400.0; }
static double lst_hours(uint32_t t, double lon) { double x = 18.697374558 + 24.06570982441908 * (julian_day(t) - 2451545.0) + lon / 15.0; x = fmod(x, 24.0); return x < 0 ? x + 24.0 : x; }
static os_horizontal_coord_t eq_to_horizontal(os_equatorial_coord_t c, uint32_t t) { double h = (lst_hours(t, site.longitude_degrees) - c.ra_hours) * OS_PI / 12.0; double lat = site.latitude_degrees * OS_PI / 180.0; double dec = c.dec_degrees * OS_PI / 180.0; double alt = asin(sin(lat) * sin(dec) + cos(lat) * cos(dec) * cos(h)); double az = atan2(sin(h), cos(h) * sin(lat) - tan(dec) * cos(lat)) + OS_PI; os_horizontal_coord_t r; r.azimuth_degrees = (float)(az * 180.0 / OS_PI); r.altitude_degrees = (float)(alt * 180.0 / OS_PI); return r; }
static os_equatorial_coord_t horizontal_to_eq(os_horizontal_coord_t h) { double az = h.azimuth_degrees * OS_PI / 180.0, alt = h.altitude_degrees * OS_PI / 180.0, lat = site.latitude_degrees * OS_PI / 180.0; double dec = asin(sin(lat) * sin(alt) - cos(lat) * cos(alt) * cos(az)); double ha = atan2(sin(az), cos(az) * sin(lat) + tan(alt) * cos(lat)); os_equatorial_coord_t r; r.ra_hours = (float)fmod(lst_hours(site.utc_epoch_seconds, site.longitude_degrees) - ha * 12.0 / OS_PI + 24.0, 24.0); r.dec_degrees = (float)(dec * 180.0 / OS_PI); return r; }
static double tracking_factor(void) { if (track_rate == OS_TRACK_RATE_LUNAR) return OS_LUNAR_RATE_FACTOR; if (track_rate == OS_TRACK_RATE_SOLAR) return OS_SOLAR_RATE_FACTOR; if (track_rate == OS_TRACK_RATE_CUSTOM) return custom_factor; return 1.0; }
static os_error_t tracking_outputs(void) { os_error_t e; double f, da, dh; if (!tracking_enabled || state == OS_STATE_PARKED || state == OS_STATE_FAULT || !time_valid) { stop_axis(0); stop_axis(1); return OS_ERR_NONE; } if (os_hal_limit_is_triggered(0) || os_hal_limit_is_triggered(1)) { stop_motion(); state = OS_STATE_FAULT; return OS_ERR_LIMIT_TRIGGERED; } if (OS_MOUNT_TYPE == OS_MOUNT_ALTAZ) { os_horizontal_coord_t h0 = eq_to_horizontal(current_coord, site.utc_epoch_seconds), h1 = eq_to_horizontal(current_coord, site.utc_epoch_seconds + 1u); da = h1.azimuth_degrees - h0.azimuth_degrees; dh = h1.altitude_degrees - h0.altitude_degrees; if (da > 180) da -= 360; if (da < -180) da += 360; e = motor_command(0, da >= 0 ? 1 : -1, frequency_for(fabs(da) * 3600.0 * tracking_factor())); if (e != OS_ERR_NONE) return e; return motor_command(1, dh >= 0 ? 1 : -1, frequency_for(fabs(dh) * 3600.0 * tracking_factor())); } f = OS_SIDEREAL_RATE_ARCSEC_PER_SEC * tracking_factor(); if (guide.active && !guide.dec_priority) { if (guide_direction == OS_DIRECTION_EAST) f += OS_SIDEREAL_RATE_ARCSEC_PER_SEC * guide.rate_fraction; if (guide_direction == OS_DIRECTION_WEST) f -= OS_SIDEREAL_RATE_ARCSEC_PER_SEC * guide.rate_fraction; } e = motor_command(0, f >= 0 ? 1 : -1, frequency_for(fabs(f))); if (e != OS_ERR_NONE) return e; if (guide.active && guide.dec_priority) return motor_command(1, guide_direction == OS_DIRECTION_NORTH ? 1 : -1, rate_frequency(guide.rate_fraction)); stop_axis(1); return OS_ERR_NONE; }
static void reset_state(void) { memset(&site, 0, sizeof site); state = OS_STATE_INITIALIZING; gps_locked = false; time_valid = false; tracking_enabled = true; track_rate = OS_TRACK_RATE_SIDEREAL; custom_factor = 1.0f; guide_rate = 0.5f; custom_move_speed = 60.0f; memset(&guide, 0, sizeof guide); guide_left = manual_left = elapsed_ms = 0; memset(&calibration, 0, sizeof calibration); residual = 0; residual_valid = false; align_mode = OS_ALIGN_1STAR; align_count = 0; memset(stars, 0, sizeof stars); memset(&pec, 0, sizeof pec); pec_enabled = false; current_coord.ra_hours = current_coord.dec_degrees = 0; target_coord = current_coord; park_coord.ra_hours = 0; park_coord.dec_degrees = 90; custom_park = false; memset(&motion, 0, sizeof motion); memset(&manual, 0, sizeof manual); memset(command_length, 0, sizeof command_length); set_ra = set_dec = 0; nvm_fault = false; }
static bool cal_valid(const cal_record_t *r) { cal_record_t x; if (r->magic != MAGIC_CAL || !r->value.valid) return false; x = *r; x.crc = 0; return r->crc == crc32((const uint8_t *)&x, sizeof x); }
static bool cfg_valid(const cfg_record_t *r) { cfg_record_t x; if (r->magic != MAGIC_CFG) return false; x = *r; x.crc = 0; return r->crc == crc32((const uint8_t *)&x, sizeof x); }
static os_error_t save_cal(const os_calibration_t *v) { cal_record_t r, q; os_error_t e; memset(&r, 0, sizeof r); r.magic = MAGIC_CAL; r.value = *v; r.crc = crc32((const uint8_t *)&r, sizeof r); e = os_hal_nvm_write(CAL_OFF, (const uint8_t *)&r, sizeof r); if (e != OS_ERR_NONE) return OS_ERR_NVM_FAULT; e = os_hal_nvm_read(CAL_OFF, (uint8_t *)&q, sizeof q); return e == OS_ERR_NONE && memcmp(&r, &q, sizeof r) == 0 ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
static os_error_t save_cfg(void) { cfg_record_t r; memset(&r, 0, sizeof r); r.magic = MAGIC_CFG; r.park = park_coord; r.site = site; r.rate = track_rate; r.custom_factor = custom_factor; r.guide_rate = guide_rate; r.move_speed = custom_move_speed; r.position = raw_position(); r.crc = crc32((const uint8_t *)&r, sizeof r); return os_hal_nvm_write(CFG_OFF, (const uint8_t *)&r, sizeof r); }
static void load_state(void) { cal_record_t c; cfg_record_t f; memset(&c, 0, sizeof c); memset(&f, 0, sizeof f); if (os_hal_nvm_read(CAL_OFF, (uint8_t *)&c, sizeof c) == OS_ERR_NONE && cal_valid(&c)) calibration = c.value; else nvm_fault = true; if (os_hal_nvm_read(CFG_OFF, (uint8_t *)&f, sizeof f) == OS_ERR_NONE && cfg_valid(&f)) { if (valid_eq(f.park)) { park_coord = f.park; custom_park = true; } if (f.site.valid) site = f.site; if (f.rate >= OS_TRACK_RATE_SIDEREAL && f.rate <= OS_TRACK_RATE_CUSTOM) track_rate = f.rate; if (finitef(f.custom_factor) && f.custom_factor > 0) custom_factor = f.custom_factor; if (finitef(f.guide_rate) && f.guide_rate >= OS_GUIDE_RATE_MIN && f.guide_rate <= OS_GUIDE_RATE_MAX) guide_rate = f.guide_rate; if (finitef(f.move_speed) && f.move_speed > 0) custom_move_speed = f.move_speed; } else nvm_fault = true; }

os_error_t os_init(void) { uint8_t i; os_error_t e, first = OS_ERR_NONE; uint32_t utc; os_site_info_t g; reset_state(); e = os_hal_nvm_init(); if (e == OS_ERR_NONE) load_state(); else nvm_fault = true; for (i = 0; i < CHANNELS; ++i) { e = os_hal_comm_init(i); if (e != OS_ERR_NONE && first == OS_ERR_NONE) first = e; } for (i = 0; i < AXES; ++i) { e = os_hal_motor_init(i); if (e != OS_ERR_NONE) { state = OS_STATE_FAULT; return OS_ERR_MOTOR_DRIVER_FAULT; } stop_axis(i); } if (os_hal_gps_init() != OS_ERR_NONE) first = OS_ERR_GPS_NO_SIGNAL; if (os_hal_rtc_init() != OS_ERR_NONE) { state = OS_STATE_FAULT; return OS_ERR_TIMEOUT; } if (os_hal_limit_init() != OS_ERR_NONE) { state = OS_STATE_FAULT; return OS_ERR_LIMIT_TRIGGERED; } if (os_hal_timer_motor_init() != OS_ERR_NONE) { state = OS_STATE_FAULT; return OS_ERR_MOTOR_DRIVER_FAULT; } memset(&g, 0, sizeof g); if (os_hal_gps_poll(&g) == OS_ERR_NONE && g.valid && g.latitude_degrees >= -90 && g.latitude_degrees <= 90 && g.longitude_degrees >= -180 && g.longitude_degrees <= 180) { site = g; gps_locked = true; time_valid = true; (void)os_hal_rtc_set(g.utc_epoch_seconds); } else if (os_hal_rtc_read(&utc) == OS_ERR_NONE) { site.utc_epoch_seconds = utc; site.valid = true; time_valid = true; } else { state = OS_STATE_FAULT; return OS_ERR_TIMEOUT; } if (os_hal_limit_is_triggered(0) || os_hal_limit_is_triggered(1)) { state = OS_STATE_FAULT; return OS_ERR_LIMIT_TRIGGERED; } state = OS_STATE_IDLE_TRACKING; return nvm_fault ? OS_ERR_NVM_FAULT : first; }
static void timer_tick(void) { uint8_t a; for (a = 0; a < AXES; ++a) if (h_motor_enabled[a] && h_motor_frequency[a] && !h_limit[a]) { h_motor_remainder[a] += (double)h_motor_frequency[a] * LOOP_MS / 1000.0; while (h_motor_remainder[a] >= 1.0) { if (h_motor_direction[a] && h_motor_position[a] < INT32_MAX) ++h_motor_position[a]; else if (!h_motor_direction[a] && h_motor_position[a] > INT32_MIN) --h_motor_position[a]; h_motor_remainder[a] -= 1.0; } } }
void os_loop_iteration(void) { uint8_t a, ch; uint32_t utc; os_site_info_t g; timer_tick(); elapsed_ms += LOOP_MS; memset(&g, 0, sizeof g); if (os_hal_gps_poll(&g) == OS_ERR_NONE && g.valid) { site = g; gps_locked = true; time_valid = true; (void)os_hal_rtc_set(g.utc_epoch_seconds); } else { gps_locked = false; if (os_hal_rtc_read(&utc) == OS_ERR_NONE) { site.utc_epoch_seconds = utc; site.valid = true; time_valid = true; } else time_valid = false; } if (elapsed_ms >= 1000u) { site.utc_epoch_seconds++; elapsed_ms -= 1000u; } for (a = 0; a < AXES; ++a) if (os_hal_limit_is_triggered(a)) { stop_axis(a); state = OS_STATE_FAULT; } if (state == OS_STATE_FAULT) return; if (guide.active) { if (guide_left <= LOOP_MS) { memset(&guide, 0, sizeof guide); guide_left = 0; } else guide_left -= LOOP_MS; } if (state == OS_STATE_GOTO && motion.active) { os_motor_position_t p = raw_position(); int64_t d[AXES]; bool done = true; d[0] = (int64_t)motion.target.ra_steps - p.ra_steps; d[1] = (int64_t)motion.target.dec_steps - p.dec_steps; for (a = 0; a < AXES; ++a) { uint64_t ad = d[a] < 0 ? (uint64_t)(-d[a]) : (uint64_t)d[a]; if (ad <= 2) stop_axis(a); else { done = false; if (motion.frequency[a] < OS_MAX_MOTOR_FREQUENCY_HZ) motion.frequency[a] += 600; if (motion.frequency[a] > OS_MAX_MOTOR_FREQUENCY_HZ) motion.frequency[a] = OS_MAX_MOTOR_FREQUENCY_HZ; if (motor_command(a, d[a] > 0 ? 1 : -1, motion.frequency[a]) != OS_ERR_NONE) { stop_motion(); state = OS_STATE_FAULT; return; } } } if (done) { bool parking = motion.parking; stop_motion(); current_coord = target_coord; (void)os_hal_buzzer_beep(100, 1); if (parking) { tracking_enabled = false; state = OS_STATE_PARKED; } else { state = OS_STATE_IDLE_TRACKING; (void)tracking_outputs(); } } } else if (state == OS_STATE_MANUAL_MOTION && manual.active) { if (manual_left <= LOOP_MS) { stop_motion(); state = OS_STATE_IDLE_TRACKING; (void)tracking_outputs(); } else { manual_left -= LOOP_MS; if (motor_command(manual.axis, manual.forward ? 1 : -1, manual.frequency) != OS_ERR_NONE) { stop_motion(); state = OS_STATE_FAULT; } } } else if (state == OS_STATE_IDLE_TRACKING) (void)tracking_outputs(); for (ch = 0; ch < CHANNELS; ++ch) { int16_t n = os_hal_comm_available(ch); while (n > 0) { char c = os_hal_comm_read(ch); if (command_length[ch] < OS_MAX_COMMAND_LENGTH) command_buffer[ch][command_length[ch]++] = c; else command_length[ch] = 0; if (c == '#') { char r[OS_MAX_REPLY_LENGTH]; size_t rn = 0; os_error_t e = os_command_parse(command_buffer[ch], command_length[ch], ch, r, sizeof r, &rn); if (rn) (void)os_hal_comm_write(ch, r, rn); else { reply_error(r, sizeof r, &rn, e); (void)os_hal_comm_write(ch, r, rn); } command_length[ch] = 0; } n = os_hal_comm_available(ch); } } }
static bool parse_ra(const char *s, float *v) { double h, m, sec; char tail; if (!s || !v || sscanf(s, "%lf:%lf:%lf%c", &h, &m, &sec, &tail) != 3) return false; if (h < 0 || h > 24 || m < 0 || m >= 60 || sec < 0 || sec >= 60 || (h == 24 && (m != 0 || sec != 0))) return false; *v = (float)(h + m / 60.0 + sec / 3600.0); return true; }
static bool parse_dec(const char *s, float *v) { char sign; double d, m, sec; if (!s || !v || sscanf(s, "%c%lf*%lf:%lf", &sign, &d, &m, &sec) != 4 || (sign != '+' && sign != '-')) return false; if (d < 0 || d > 90 || m < 0 || m >= 60 || sec < 0 || sec >= 60 || (d == 90 && (m != 0 || sec != 0))) return false; *v = (float)((sign == '-' ? -1.0 : 1.0) * (d + m / 60.0 + sec / 3600.0)); return true; }
os_error_t os_command_parse(const char *cmd, size_t n, uint8_t ch, char *reply, size_t z, size_t *rn) { char s[OS_MAX_COMMAND_LENGTH], out[64]; os_equatorial_coord_t c; os_error_t e = OS_ERR_COMMAND_FORMAT; if (!cmd || !reply || !rn) return OS_ERR_INVALID_ARGUMENT; *rn = 0; if (!valid_channel(ch) || n < 3 || n > OS_MAX_COMMAND_LENGTH || cmd[0] != ':' || cmd[n - 1] != '#') { reply_error(reply, z, rn, OS_ERR_COMMAND_FORMAT); return OS_ERR_COMMAND_FORMAT; } if (n - 2 >= sizeof s) { reply_error(reply, z, rn, OS_ERR_COMMAND_FORMAT); return OS_ERR_COMMAND_FORMAT; } memcpy(s, cmd + 1, n - 2); s[n - 2] = 0; if (!strcmp(s, "GVP")) reply_text(reply, z, rn, "OnStep 1.0.0#"); else if (!strcmp(s, "GR")) { os_query_coordinates(&c); snprintf(out, sizeof out, "%02d:%02d:%02d#", (int)c.ra_hours, (int)(c.ra_hours * 60) % 60, (int)(c.ra_hours * 3600) % 60); reply_text(reply, z, rn, out); } else if (!strcmp(s, "GD")) { double x; os_query_coordinates(&c); x = fabs(c.dec_degrees); snprintf(out, sizeof out, "%c%02d*%02d:%02d#", c.dec_degrees < 0 ? '-' : '+', (int)x, (int)(x * 60) % 60, (int)(x * 3600) % 60); reply_text(reply, z, rn, out); } else if (s[0] == 'S' && s[1] == 'r') { e = parse_ra(s + 2, &set_ra) ? OS_ERR_NONE : OS_ERR_INVALID_ARGUMENT; if (e == OS_ERR_NONE) reply_text(reply, z, rn, "1#"); } else if (s[0] == 'S' && s[1] == 'd') { e = parse_dec(s + 2, &set_dec) ? OS_ERR_NONE : OS_ERR_INVALID_ARGUMENT; if (e == OS_ERR_NONE) reply_text(reply, z, rn, "1#"); } else if (!strcmp(s, "MS")) { c.ra_hours = set_ra; c.dec_degrees = set_dec; e = os_goto_equatorial(c); reply_text(reply, z, rn, e == OS_ERR_NONE ? "0#" : "1#"); } else if (!strcmp(s, "Q")) { e = state == OS_STATE_GOTO ? os_goto_abort() : os_move_stop(); reply_text(reply, z, rn, "1#"); } else if (!strcmp(s, "hP")) { e = os_park(); reply_text(reply, z, rn, e == OS_ERR_NONE ? "1#" : "0#"); } else if (!strcmp(s, "hO")) { e = os_unpark(); reply_text(reply, z, rn, e == OS_ERR_NONE ? "1#" : "0#"); } else if (s[0] == 'M' && s[1]) { os_direction_t d; if (s[1] == 'e') d = OS_DIRECTION_EAST; else if (s[1] == 'w') d = OS_DIRECTION_WEST; else if (s[1] == 'n') d = OS_DIRECTION_NORTH; else if (s[1] == 's') d = OS_DIRECTION_SOUTH; else { reply_error(reply, z, rn, OS_ERR_COMMAND_FORMAT); return OS_ERR_COMMAND_FORMAT; } e = os_move_start(d, OS_SPEED_MEDIUM); reply_text(reply, z, rn, e == OS_ERR_NONE ? "1#" : "0#"); } else reply_error(reply, z, rn, e); if (!*rn) reply_error(reply, z, rn, e); return e; }
os_error_t os_goto_equatorial(os_equatorial_coord_t t) { os_motor_position_t p, q; int64_t a, b; if (!valid_eq(t)) return OS_ERR_INVALID_ARGUMENT; if (state == OS_STATE_PARKED || state == OS_STATE_FAULT || state == OS_STATE_ALIGNMENT) return OS_ERR_INVALID_STATE; p = raw_position(); q = to_steps(t, &calibration); a = (int64_t)q.ra_steps - p.ra_steps; b = (int64_t)q.dec_steps - p.dec_steps; if ((a && blocked(0, a > 0)) || (b && blocked(1, b > 0))) return OS_ERR_LIMIT_TRIGGERED; target_coord = t; if (llabs(a) <= 2 && llabs(b) <= 2) { current_coord = t; return OS_ERR_NONE; } memset(&motion, 0, sizeof motion); motion.active = true; motion.target = q; state = OS_STATE_GOTO; stop_axis(0); stop_axis(1); return OS_ERR_NONE; }
os_error_t os_goto_horizontal(os_horizontal_coord_t t) { os_equatorial_coord_t e; if (!finitef(t.azimuth_degrees) || !finitef(t.altitude_degrees) || t.azimuth_degrees < 0 || t.azimuth_degrees > 360 || t.altitude_degrees < -90 || t.altitude_degrees > 90) return OS_ERR_INVALID_ARGUMENT; if (!time_valid || !site.valid) return OS_ERR_INVALID_STATE; if (OS_MOUNT_TYPE == OS_MOUNT_ALTAZ) e = horizontal_to_eq(t); else { e.ra_hours = t.azimuth_degrees / 15.0f; e.dec_degrees = t.altitude_degrees; } return os_goto_equatorial(e); }
os_error_t os_goto_abort(void) { if (state != OS_STATE_GOTO) return OS_ERR_INVALID_STATE; stop_motion(); state = OS_STATE_IDLE_TRACKING; return tracking_outputs(); }
os_error_t os_tracking_set_rate(os_track_rate_t r, float f) { os_error_t e; if (r < OS_TRACK_RATE_SIDEREAL || r > OS_TRACK_RATE_CUSTOM || !finitef(f) || (r == OS_TRACK_RATE_CUSTOM && f <= 0)) return OS_ERR_INVALID_ARGUMENT; track_rate = r; if (r == OS_TRACK_RATE_CUSTOM) custom_factor = f; e = save_cfg(); if (e != OS_ERR_NONE) return OS_ERR_NVM_FAULT; return tracking_outputs(); }
os_error_t os_tracking_get_rate(os_track_rate_t *r, float *f) { if (!r || !f) return OS_ERR_INVALID_ARGUMENT; *r = track_rate; *f = custom_factor; return OS_ERR_NONE; }
os_error_t os_tracking_enable(void) { if (state == OS_STATE_PARKED || state == OS_STATE_FAULT || !time_valid) return OS_ERR_INVALID_STATE; tracking_enabled = true; return tracking_outputs(); }
os_error_t os_tracking_disable(void) { tracking_enabled = false; stop_axis(0); stop_axis(1); return OS_ERR_NONE; }
os_error_t os_guide_pulse(os_direction_t d, uint32_t ms) { if (!valid_direction(d) || ms == 0) return OS_ERR_INVALID_ARGUMENT; if (state == OS_STATE_PARKED || state == OS_STATE_FAULT) return OS_ERR_INVALID_STATE; if (guide.active && guide.dec_priority && (d == OS_DIRECTION_EAST || d == OS_DIRECTION_WEST)) return OS_ERR_INVALID_STATE; memset(&guide, 0, sizeof guide); guide.active = true; guide.duration_ms = ms; guide.rate_fraction = guide_rate; guide.direction_east = d == OS_DIRECTION_EAST; guide.direction_north = d == OS_DIRECTION_NORTH; guide.dec_priority = d == OS_DIRECTION_NORTH || d == OS_DIRECTION_SOUTH; guide_direction = d; guide_left = ms; return tracking_outputs(); }
os_error_t os_guide_set_rate(float f) { os_error_t e; if (!finitef(f) || f < OS_GUIDE_RATE_MIN || f > OS_GUIDE_RATE_MAX) return OS_ERR_INVALID_ARGUMENT; guide_rate = f; e = save_cfg(); return e == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
os_error_t os_guide_get_state(os_guide_pulse_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = guide; return OS_ERR_NONE; }
os_error_t os_align_begin(os_align_mode_t m) { if (m < OS_ALIGN_1STAR || m > OS_ALIGN_NSTAR) return OS_ERR_INVALID_ARGUMENT; align_mode = m; align_count = 0; residual_valid = false; state = OS_STATE_ALIGNMENT; stop_motion(); return OS_ERR_NONE; }
os_error_t os_align_accept_star(os_equatorial_coord_t c, os_motor_position_t p) { if (!valid_eq(c)) return OS_ERR_INVALID_ARGUMENT; if (state != OS_STATE_ALIGNMENT || align_count >= OS_CALIBRATION_MAX_STARS) return OS_ERR_INVALID_STATE; stars[align_count].c = c; stars[align_count].p = p; ++align_count; return OS_ERR_NONE; }
static bool solve3(double a[3][4], double x[3]) { int i, j, k, p; double t, m, q; for (i = 0; i < 3; ++i) { p = i; for (j = i + 1; j < 3; ++j) if (fabs(a[j][i]) > fabs(a[p][i])) p = j; if (fabs(a[p][i]) < 1e-12) return false; if (p != i) for (k = i; k < 4; ++k) { t = a[i][k]; a[i][k] = a[p][k]; a[p][k] = t; } for (j = i + 1; j < 3; ++j) { m = a[j][i] / a[i][i]; for (k = i; k < 4; ++k) a[j][k] -= m * a[i][k]; } } for (i = 2; i >= 0; --i) { q = a[i][3]; for (j = i + 1; j < 3; ++j) q -= a[i][j] * x[j]; x[i] = q / a[i][i]; } return true; }
os_error_t os_align_compute(void) { double a[3][4], x[3], y[3], det, rss = 0; os_calibration_t n; int i; uint8_t min = align_mode == OS_ALIGN_1STAR ? 1 : align_mode == OS_ALIGN_2STAR ? 2 : 3; if (align_count < min) return OS_ERR_INVALID_STATE; memset(&n, 0, sizeof n); if (align_mode == OS_ALIGN_1STAR) { n.matrix_ra_to_ra = n.matrix_dec_to_dec = 1; n.offset_ra_arcsec = (float)(stars[0].p.ra_steps - ra_arcsec(stars[0].c) * OS_STEPS_PER_ARCSEC); n.offset_dec_arcsec = (float)(stars[0].p.dec_steps - dec_arcsec(stars[0].c) * OS_STEPS_PER_ARCSEC); } else if (align_mode == OS_ALIGN_2STAR) { double dr = ra_arcsec(stars[1].c) - ra_arcsec(stars[0].c), dd = dec_arcsec(stars[1].c) - dec_arcsec(stars[0].c); if (fabs(dr) < 1e-12 || fabs(dd) < 1e-12) return OS_ERR_CALIBRATION_FAILED; n.matrix_ra_to_ra = (float)((stars[1].p.ra_steps - stars[0].p.ra_steps) / (dr * OS_STEPS_PER_ARCSEC)); n.matrix_dec_to_dec = (float)((stars[1].p.dec_steps - stars[0].p.dec_steps) / (dd * OS_STEPS_PER_ARCSEC)); n.offset_ra_arcsec = (float)(stars[0].p.ra_steps / OS_STEPS_PER_ARCSEC - n.matrix_ra_to_ra * ra_arcsec(stars[0].c)); n.offset_dec_arcsec = (float)(stars[0].p.dec_steps / OS_STEPS_PER_ARCSEC - n.matrix_dec_to_dec * dec_arcsec(stars[0].c)); } else { for (i = 0; i < 3; ++i) { a[i][0] = ra_arcsec(stars[i].c); a[i][1] = dec_arcsec(stars[i].c); a[i][2] = 1; a[i][3] = stars[i].p.ra_steps / OS_STEPS_PER_ARCSEC; } det = (a[1][0] - a[0][0]) * (a[2][1] - a[0][1]) - (a[2][0] - a[0][0]) * (a[1][1] - a[0][1]); if (fabs(det) < 1e-12 * fmax(1.0, fabs(a[1][0] - a[0][0]) * fabs(a[2][1] - a[0][1]))) return OS_ERR_CALIBRATION_FAILED; if (!solve3(a, x)) return OS_ERR_CALIBRATION_FAILED; for (i = 0; i < 3; ++i) { a[i][0] = ra_arcsec(stars[i].c); a[i][1] = dec_arcsec(stars[i].c); a[i][2] = 1; a[i][3] = stars[i].p.dec_steps / OS_STEPS_PER_ARCSEC; } if (!solve3(a, y)) return OS_ERR_CALIBRATION_FAILED; n.matrix_ra_to_ra = (float)x[0]; n.matrix_dec_to_ra = (float)x[1]; n.offset_ra_arcsec = (float)x[2]; n.matrix_ra_to_dec = (float)y[0]; n.matrix_dec_to_dec = (float)y[1]; n.offset_dec_arcsec = (float)y[2]; } n.valid = true; for (i = 0; i < align_count; ++i) { os_motor_position_t p = to_steps(stars[i].c, &n); double u = p.ra_steps - stars[i].p.ra_steps, v = p.dec_steps - stars[i].p.dec_steps; rss += u * u + v * v; } residual = (float)sqrt(rss / align_count) / (float)OS_STEPS_PER_ARCSEC; if (align_count >= 4 && residual > 300.0f) return OS_ERR_CALIBRATION_FAILED; if (save_cal(&n) != OS_ERR_NONE) return OS_ERR_NVM_FAULT; calibration = n; residual_valid = true; state = OS_STATE_IDLE_TRACKING; return OS_ERR_NONE; }
os_error_t os_align_get_residual(float *r) { if (!r) return OS_ERR_INVALID_ARGUMENT; if (!residual_valid) return OS_ERR_INVALID_STATE; *r = residual; return OS_ERR_NONE; }
os_error_t os_align_abort(void) { if (state != OS_STATE_ALIGNMENT) return OS_ERR_INVALID_STATE; align_count = 0; residual_valid = false; state = OS_STATE_IDLE_TRACKING; return OS_ERR_NONE; }
os_error_t os_park(void) { os_error_t e; os_equatorial_coord_t p; if (os_hal_limit_is_triggered(0) || os_hal_limit_is_triggered(1)) return OS_ERR_LIMIT_TRIGGERED; p = custom_park ? park_coord : (os_equatorial_coord_t){0, 90}; e = os_goto_equatorial(p); if (e == OS_ERR_NONE && state == OS_STATE_GOTO) motion.parking = true; else if (e == OS_ERR_NONE) { tracking_enabled = false; state = OS_STATE_PARKED; stop_motion(); } return e; }
os_error_t os_unpark(void) { uint8_t i; uint32_t t; if (state != OS_STATE_PARKED) return OS_ERR_INVALID_STATE; for (i = 0; i < AXES; ++i) if (os_hal_motor_init(i) != OS_ERR_NONE) { state = OS_STATE_FAULT; return OS_ERR_MOTOR_DRIVER_FAULT; } for (i = 0; i < CHANNELS; ++i) (void)os_hal_comm_init(i); if (os_hal_rtc_read(&t) != OS_ERR_NONE) return OS_ERR_INVALID_STATE; site.utc_epoch_seconds = t; time_valid = true; tracking_enabled = true; state = OS_STATE_IDLE_TRACKING; return tracking_outputs(); }
os_error_t os_park_set_position(os_equatorial_coord_t p) { if (!valid_eq(p)) return OS_ERR_INVALID_ARGUMENT; park_coord = p; custom_park = true; return save_cfg() == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
os_error_t os_move_start(os_direction_t d, os_speed_level_t s) { uint32_t f; if (!valid_direction(d) || s < OS_SPEED_SLOW || s > OS_SPEED_CUSTOM) return OS_ERR_INVALID_ARGUMENT; if (state == OS_STATE_PARKED || state == OS_STATE_FAULT) return OS_ERR_INVALID_STATE; manual.axis = (d == OS_DIRECTION_EAST || d == OS_DIRECTION_WEST) ? 0 : 1; manual.forward = d == OS_DIRECTION_EAST || d == OS_DIRECTION_NORTH; if (blocked(manual.axis, manual.forward)) return OS_ERR_LIMIT_TRIGGERED; f = frequency_for(s == OS_SPEED_SLOW ? OS_MANUAL_SPEED_SLOW_ARCSEC : s == OS_SPEED_MEDIUM ? OS_MANUAL_SPEED_MEDIUM_ARCSEC : s == OS_SPEED_FAST ? OS_MANUAL_SPEED_FAST_ARCSEC : custom_move_speed); manual.frequency = f; manual.active = true; manual_left = MANUAL_TIMEOUT_MS; state = OS_STATE_MANUAL_MOTION; return OS_ERR_NONE; }
os_error_t os_move_stop(void) { stop_motion(); if (state == OS_STATE_GOTO || state == OS_STATE_MANUAL_MOTION) state = OS_STATE_IDLE_TRACKING; return tracking_outputs(); }
os_error_t os_move_set_custom_speed(float s) { if (!finitef(s) || s <= 0) return OS_ERR_INVALID_ARGUMENT; custom_move_speed = s; return save_cfg() == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
os_error_t os_query_state(os_state_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = state; return OS_ERR_NONE; }
os_error_t os_query_coordinates(os_equatorial_coord_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = from_steps(raw_position()); return OS_ERR_NONE; }
os_error_t os_query_site(os_site_info_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = site; return OS_ERR_NONE; }
os_error_t os_query_motor_position(os_motor_position_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = raw_position(); return OS_ERR_NONE; }
os_error_t os_query_firmware_version(uint8_t *a, uint8_t *b, uint8_t *c) { if (!a || !b || !c) return OS_ERR_INVALID_ARGUMENT; *a = OS_FIRMWARE_VERSION_MAJOR; *b = OS_FIRMWARE_VERSION_MINOR; *c = OS_FIRMWARE_VERSION_PATCH; return OS_ERR_NONE; }
os_error_t os_query_is_moving(bool *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = motion.active || manual.active || state == OS_STATE_GOTO || state == OS_STATE_MANUAL_MOTION; return OS_ERR_NONE; }
os_error_t os_query_gps_locked(bool *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = gps_locked; return OS_ERR_NONE; }
os_error_t os_pec_enable(bool e) { if (e && !pec.valid) return OS_ERR_INVALID_STATE; pec_enabled = e; return tracking_outputs(); }
os_error_t os_pec_load_table(const os_pec_table_t *p) { if (!p || !p->valid) return OS_ERR_INVALID_ARGUMENT; pec = *p; return os_hal_nvm_write(PEC_OFF, (const uint8_t *)&pec, sizeof pec) == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
os_error_t os_pec_get_table(os_pec_table_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = pec; return OS_ERR_NONE; }
os_error_t os_pec_record_phase(float phase, int16_t error) { int i; if (!finitef(phase) || phase < 0 || phase > 360) return OS_ERR_INVALID_ARGUMENT; i = phase >= 360 ? 0 : (int)phase; pec.corrections[i] = error; pec.valid = true; return os_hal_nvm_write(PEC_OFF, (const uint8_t *)&pec, sizeof pec) == OS_ERR_NONE ? OS_ERR_NONE : OS_ERR_NVM_FAULT; }
os_error_t os_calibration_get(os_calibration_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; *p = calibration; return OS_ERR_NONE; }
os_error_t os_calibration_clear(void) { os_calibration_t z; memset(&z, 0, sizeof z); if (save_cal(&z) != OS_ERR_NONE) return OS_ERR_NVM_FAULT; calibration = z; residual_valid = false; return OS_ERR_NONE; }

os_error_t os_hal_motor_init(uint8_t a) { if (!valid_axis(a)) return OS_ERR_INVALID_ARGUMENT; h_motor_initialized[a] = true; h_motor_enabled[a] = false; h_motor_frequency[a] = 0; h_motor_remainder[a] = 0; return OS_ERR_NONE; }
os_error_t os_hal_motor_set_frequency(uint8_t a, uint32_t f) { if (!valid_axis(a) || !h_motor_initialized[a]) return OS_ERR_INVALID_ARGUMENT; if (f > OS_MAX_MOTOR_FREQUENCY_HZ) f = OS_MAX_MOTOR_FREQUENCY_HZ; h_motor_frequency[a] = f; return OS_ERR_NONE; }
os_error_t os_hal_motor_set_direction(uint8_t a, bool f) { if (!valid_axis(a) || !h_motor_initialized[a]) return OS_ERR_INVALID_ARGUMENT; h_motor_direction[a] = f; return OS_ERR_NONE; }
os_error_t os_hal_motor_enable(uint8_t a, bool e) { if (!valid_axis(a) || !h_motor_initialized[a]) return OS_ERR_INVALID_ARGUMENT; h_motor_enabled[a] = e; if (!e) h_motor_frequency[a] = 0; return OS_ERR_NONE; }
int32_t os_hal_motor_get_position(uint8_t a) { return valid_axis(a) ? h_motor_position[a] : 0; }
os_error_t os_hal_gps_init(void) { h_gps_ready = true; return OS_ERR_NONE; }
os_error_t os_hal_gps_poll(os_site_info_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; if (!h_gps_ready || !h_gps_site.valid) { memset(p, 0, sizeof *p); return OS_ERR_GPS_NO_SIGNAL; } *p = h_gps_site; return OS_ERR_NONE; }
os_error_t os_hal_rtc_init(void) { h_rtc_ready = true; if (!h_rtc_epoch) h_rtc_epoch = 1; return OS_ERR_NONE; }
os_error_t os_hal_rtc_read(uint32_t *p) { if (!p) return OS_ERR_INVALID_ARGUMENT; if (!h_rtc_ready) return OS_ERR_TIMEOUT; *p = h_rtc_epoch; return OS_ERR_NONE; }
os_error_t os_hal_rtc_set(uint32_t t) { if (!h_rtc_ready) return OS_ERR_TIMEOUT; h_rtc_epoch = t; return OS_ERR_NONE; }
os_error_t os_hal_limit_init(void) { return OS_ERR_NONE; }
bool os_hal_limit_is_triggered(uint8_t a) { return !valid_axis(a) || h_limit[a]; }
os_error_t os_hal_nvm_init(void) { h_nvm_ready = true; return OS_ERR_NONE; }
os_error_t os_hal_nvm_read(uint16_t o, uint8_t *p, uint16_t n) { if (!p) return OS_ERR_INVALID_ARGUMENT; if (!h_nvm_ready) return OS_ERR_NVM_FAULT; if ((uint32_t)o + n > NVM_TOTAL) return OS_ERR_INVALID_ARGUMENT; memcpy(p, h_nvm + o, n); return OS_ERR_NONE; }
os_error_t os_hal_nvm_write(uint16_t o, const uint8_t *p, uint16_t n) { if (!p) return OS_ERR_INVALID_ARGUMENT; if (!h_nvm_ready) return OS_ERR_NVM_FAULT; if ((uint32_t)o + n > NVM_TOTAL) return OS_ERR_INVALID_ARGUMENT; memcpy(h_nvm + o, p, n); return OS_ERR_NONE; }
os_error_t os_hal_comm_init(uint8_t c) { if (!valid_channel(c)) return OS_ERR_INVALID_ARGUMENT; h_rx_head[c] = h_rx_tail[c] = h_tx_length[c] = 0; return OS_ERR_NONE; }
int16_t os_hal_comm_available(uint8_t c) { if (!valid_channel(c)) return -1; return (int16_t)(h_rx_tail[c] - h_rx_head[c]); }
char os_hal_comm_read(uint8_t c) { size_t i; if (!valid_channel(c) || h_rx_head[c] >= h_rx_tail[c]) return 0; i = h_rx_head[c]++ % sizeof h_rx[c]; return h_rx[c][i]; }
os_error_t os_hal_comm_write(uint8_t c, const char *p, size_t n) { if (!valid_channel(c) || !p) return OS_ERR_INVALID_ARGUMENT; if (n > sizeof h_tx[c] - h_tx_length[c]) return OS_ERR_TIMEOUT; memcpy(h_tx[c] + h_tx_length[c], p, n); h_tx_length[c] += n; return OS_ERR_NONE; }
os_error_t os_hal_buzzer_beep(uint16_t d, uint8_t n) { uint8_t next; if (!n) return OS_ERR_NONE; next = (uint8_t)((h_buzzer_tail + 1u) % 8u); if (next == h_buzzer_head) return OS_ERR_TIMEOUT; h_buzzer[h_buzzer_tail].duration = d; h_buzzer[h_buzzer_tail].count = n; h_buzzer_tail = next; return OS_ERR_NONE; }
os_error_t os_hal_timer_motor_init(void) { memset(h_motor_remainder, 0, sizeof h_motor_remainder); return OS_ERR_NONE; }